MTES-MCT/monitorenv

frontend/src/domain/shared_slices/Map.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearch.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearch.slice.js, frontend/src/features/layers/regulatory/search/RegulatoryLayerSearchInput.js, frontend/src/features/map/MapHistory.js
add CurrentMapExtentTracker controlled by maphistory
=> Frontend - filter searched regulatory layers on map extent

datascience/src/pipeline/queries/cross/regulations.sql, infra/cacem/contraintes_table_reglementation.sql
Script d'import permet de s'assurer que les données importées ne contiennent pas de champs null Script d'ajout de contraintes sur la reg pour interdire certains champs null
=> fix(reg): champs non null pour la reg

backend/pom.xml, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/health/Health.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IRegulatoryAreaRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/crud/healthcheck/GetHealthcheck.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/outputs/HealthDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/HealthcheckController.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/VersionController.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaRegulatoryAreaRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBRegulatoryAreaRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/HealthcheckControllerITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaRegulatoryAreaRepositoryITests.kt
healthcheck on:
- regulatory areas
- missions
=> add version + healthcheck endpoints

Makefile, frontend/package.json
ci broken after change in package.json (coherence with monitorfish)
=> fix ci (test command)

frontend/package-lock.json, frontend/package.json, frontend/src/uiMonitor/CustomFormikFields/FormikDatePicker.tsx
=> fix(monitor-ui): datepicker to handle string date

frontend/cypress/e2e/side_window_missions.spec.ts, frontend/src/features/missions/MissionForm/ActionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionFormHeaderVehicle.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionsForm.tsx, frontend/src/features/missions/Missions.helpers.ts, frontend/src/features/missions/MissionsList/CellEditMission.tsx
- Resolve #170 
- Resolve #108
=> Add duplicate of control infraction

backend/src/main/resources/db/migration/internal/V0.068__add_mission_order_column_to_missions_table.sql
=> Add mission_order column to missions table

frontend/cypress/e2e/side_window_missions.spec.ts, frontend/src/domain/entities/controlUnit.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionsForm.tsx, frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx, frontend/src/features/missions/Missions.helpers.ts, frontend/src/features/missions/Missions.tsx, frontend/src/features/missions/MultiPointPicker.tsx, frontend/src/uiMonitor/CustomRsuite/SelectPicker.tsx
- Resolve #170 
- Resolve #343
- Resolve #204 
- Resolve #334
=> Missions control units update and infractions styling

datascience/src/pipeline/queries/fmc/control_units.sql
=> handle dupicated administrations in integration

frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/ActionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/ui/Table/Cell/DateCell.tsx, frontend/src/utils/getDateAsLocalizedString.tsx
=> fix(missions): format date using dayjs

frontend/src/features/missions/MissionForm/ActionForm/Themes/SubThemesSelector.tsx
=> fix(sous-thématiques): afficher toutes les sous thématiques

frontend/cypress/e2e/side_window_missions.spec.ts, frontend/src/features/missions/CreateOrEditMission.tsx, frontend/src/features/missions/MissionForm/ActionForm/ActionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx
=> Thomas/fix bugs v1.6.0

README.md, infra/.env.example, infra/init/postgis_insert_layers.sh
- Mise à jour du Readme
- Suppression d'un espace pour la constante `GEOSERVER_HOST` dans .env.example
- Suppression de `Control Resources` dans postgis_insert_layers.sh
=> [Readme] Update Readme and delete useless space in.env.example

frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx
=> [ResourceUnit] delete possibility to create new resource unit

frontend/src/features/missions/MultiZonePicker.tsx
=> [EditZone] Fixed a crash when deleting a mission area

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMonitorEnvMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsController.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsControllerITests.kt, frontend/cypress/e2e/side_window_missions.spec.ts, frontend/src/api/missionsAPI.ts, frontend/src/domain/entities/missions.ts, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/features/map/layers/missionGeometryHelpers.ts, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/OverlayPositionOnExtent.tsx, frontend/src/features/map/overlays/missions/MissionCard.tsx, frontend/src/features/missions/CreateOrEditMission.tsx, frontend/src/features/missions/MissionsList/CellMissionSource.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/features/missions/MissionsList/MissionsTableFilters.tsx, frontend/src/hooks/useGetFilteredMissionsQuery.ts, frontend/src/ui/MissionSourceTag.tsx
- Resolve #402
- Ajout du tag de la source sur la pop-up de mission
- Ajout d'une colonne et d'un filtre origine dans le tableau des missions
- Ajout du tag de la source dans le header de la page d'une mission
=> [MissionSource] Display mission source

frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/actions/ControlCard.tsx, frontend/src/features/map/overlays/missions/MissionCard.tsx
- Resolve #140
Traitement de retours : https://github.com/MTES-MCT/monitorenv/issues/140#issuecomment-1505614316
=> [Control] improve control pop-up

frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
=> [Mission] add isEndDate prop for the mission end time

frontend/src/features/map/overlays/actions/ControlCard.tsx
Mise en gris du texte "A renseigner" dans la pop-up de contrôle
- Retour sur le #140
=> [Style] Display text in gray when value is empty ("A renseigner")

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/missions/MissionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/inputs/CreateOrUpdatePublicMissionDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/outputs/MissionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsController.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt, backend/src/main/resources/db/migration/internal/V0.073__alter_missions_table.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/UpdateMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsControllerITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt
=> [Mission] add hasMissionOrder & isUnderJdp props to mission entity

frontend/package-lock.json, frontend/package.json, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MultiZonePicker.tsx
=> [SurveillanceZone] Disabled coverMissionZone field if custom zone set

frontend/cypress/e2e/side_window_mission.spec.ts, frontend/src/domain/use_cases/missions/deleteMission.ts, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx
=> [Mission] Résolution du bug empêchant la suppression d'une mission

frontend/cypress/e2e/side_window_mission.spec.ts, frontend/src/features/missions/MissionSchema.ts
=> [Mission] Possibilité de clôturer une mission sans contact

frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx
- Traitement du retour de la #407
=> [Mission] Afficher l'ordre de mission et mission sous JDP seulement pour les missions CNSP

frontend/cypress/e2e/side_window_mission.spec.ts, frontend/cypress/e2e/side_window_missions.spec.ts, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx
=> [Mission] Rendre inactif le bouton de suppression de mission pour les missions du CNSP

frontend/src/domain/use_cases/draw/addFeatureToDrawedFeature.ts, frontend/src/features/map/overlays/actions/ControlCard.tsx, frontend/src/features/map/overlays/actions/SurveillanceCard.tsx, frontend/src/features/missions/MultiPointPicker.tsx
=> [ControlAction] Ne pouvoir ajouter qu'un seul point de contrôle

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt
- Resolve https://github.com/MTES-MCT/monitorfish/issues/2096
=> [MissionFilter] Résolution du bug sur le filtre des statuts de mission

frontend/cypress/e2e/01_side_window_mission.spec.ts, frontend/src/features/missions/MissionsList/CellLocalizeMission.tsx, frontend/src/features/missions/MissionsList/Columns.tsx, frontend/src/features/missions/MissionsList/Columns/Skeleton.tsx, frontend/src/features/missions/MissionsList/Columns/index.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/features/missions/MissionsList/index.tsx, frontend/src/hooks/useGetFilteredMissionsQuery.ts
=> [Missions] Affichage de la période sélectionnée précédemment et ajout d'un loader au changement de filtre

backend/src/main/resources/db/migration/internal/V0.082__alter_envactions_table.sql
- Je supprime également les ressources et unités liées aux missions de 2002
=> [Data] Suppression des ressources et unités liées aux missions de 2022

frontend/src/components/ErrorToastNotification.tsx, frontend/src/domain/use_cases/missions/createOrEditMission.ts, frontend/src/features/SideWindow/index.tsx, frontend/src/pages/HomePage.tsx
proposition en attendant d'intégrer le module de gestion d'erreur de monitor-ui
=> [Missions] notification erreurs d'enregistrement de mission sur la sidewindow

datascience/src/pipeline/queries/monitorenv/update_actions_departments.sql, datascience/src/pipeline/queries/monitorenv/update_actions_facades.sql, datascience/src/pipeline/queries/monitorenv/update_missions_facades.sql
=> Handle invalid geometries when attributing departments and facades

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/missions/EnvActionControlProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/missions/EnvActionSurveillanceProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/EnvActionMapper.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/EnvActionModel.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt, datascience/src/pipeline/queries/monitorenv/update_actions_departments.sql, datascience/src/pipeline/queries/monitorenv/update_actions_facades.sql
=> Fix et amélioration des attributions de façade et de département aux env_actions

backend/src/main/resources/db/migration/internal/V0.086__delete_cnsp_test_missions.sql
=> Supprimer les missions créées depuis Monitorfish pendant la phase de test

frontend/src/features/SideWindow/index.tsx, frontend/src/features/missions/MissionForm/index.tsx
=> [Mission] Résolution du problème de largeur de la sideWindow

frontend/src/features/missions/MissionForm/Schemas/index.ts
=> [Mission] Possibilité de n'ajouter qu'un contact en cas de mission conjointe avec plusieurs unités

frontend/package-lock.json, frontend/package.json, frontend/src/domain/shared_slices/Draw.ts, frontend/src/features/map/draw/DrawModal.tsx, frontend/src/utils/geometryValidation.ts
Vérifie les intersections et les points en double qui peuvent poser des soucis lors du calcul des façades et autres croisements de PostGis
=> [Missions] Validation des géométries de zone de mission et de surveillance

frontend/package-lock.json, frontend/package.json
=> [Date picker] Problème de saisie de l'heure au clavier

frontend/src/domain/shared_slices/Draw.ts, frontend/src/utils/geometryValidation.test.ts, frontend/src/utils/geometryValidation.ts
named imports for lodash
lowercase for functions
=> [Tech] ajout de tests sur la validation des géométries

frontend/src/features/layersSelector/search/index.tsx
=> [REG/AMP] amélioration de la recherche des couches

frontend/src/api/reportingsAPI.ts, frontend/src/features/Reportings/ReportingsList/Columns/index.tsx
=> [Reportings] Résolution du bug de tri du tableau par statut

frontend/src/domain/use_cases/missions/addMission.ts, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/utils/getMissionTitle.ts
- Resolve #738 
- Resolve #721
=> [Mission] Sauvegarder la mission en cours à l'ajout d'une mission depuis la carte + ajout de l'unité dans l'entête d'une nouvelle mission

frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/shared_slices/SelectedAmp.ts, frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx, frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/index.tsx, frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx, frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts, frontend/src/features/map/layers/AMP/index.ts, frontend/src/features/map/overlays/reportings/ReportingCard.tsx
=> [AMP] Scroller dans la liste de recherche des AMP à la sélection d'une AMP sur la carte

frontend/src/features/missions/Missions.helpers.ts, frontend/src/ui/ControlInfractionsTags.tsx
=> [Mission] Affichage du tag "1 INF EN ATTENTE DE PV" dans la colonne résumé de la mission

frontend/cypress/e2e/03_side_window_missions_navigation.spec.ts, frontend/public/archived_reporting_infraction.svg, frontend/public/archived_reporting_observation.svg, frontend/public/semaphore.svg, frontend/src/constants/constants.js, frontend/src/domain/shared_slices/SemaphoresSlice.ts, frontend/src/domain/use_cases/draw/drawGeometry.ts, frontend/src/domain/use_cases/reportings/saveReporting.ts, frontend/src/features/Reportings/ReportingForm/Source.tsx, frontend/src/features/map/layers/Missions/index.tsx, frontend/src/features/map/layers/Missions/missions.style.ts, frontend/src/features/map/layers/Reportings/style.ts, frontend/src/features/map/layers/Semaphores/index.ts, frontend/src/features/map/layers/Semaphores/semaphores.style.ts, frontend/src/features/map/layers/Semaphores/semaphoresGeometryHelpers.ts, frontend/src/features/map/overlays/reportings/ReportingCard.tsx, frontend/src/features/map/overlays/reportings/index.tsx
=> [Reporting] Diverses corrections de style

frontend/cypress/e2e/02_side_window_mission_actions.spec.ts, frontend/cypress/e2e/04_create_reporting.spec.ts, frontend/src/domain/entities/targetType.ts, frontend/src/features/Reportings/ReportingForm/Target/TargetDetails.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionFormHeaderCompany.tsx
=> [Wording] Changement du terme "Société" par "Personne morale" (mission et signalement)

datascience/src/pipeline/queries/fmc/natinf.sql
=> [Natinf] Modification pour ne pas remonter dans Env les natinfs "bloqués" dans Poséidon

frontend/src/features/missions/MissionForm/Schemas/Surveillance.ts, frontend/src/features/missions/MultiZonePicker.tsx
=> [Mission] Zone de surveillance obligatoire en cas de clôture de mission

frontend/src/features/map/tools/measurements/CustomCircleRange.tsx
=> [Measurement] Amélioration de l'outil de tracé de cercle

frontend/src/features/missions/Missions.helpers.ts, frontend/src/ui/ControlInfractionsTags.tsx
=> [Mission] Mise à jour des tags "Infractions"

.gitignore, datascience/src/pipeline/data/dummy_area_notes.csv, datascience/src/pipeline/data/dummy_terms_notes.csv, datascience/src/pipeline/flows/control_resources_bases_contacts.py, datascience/tests/test_pipeline/test_flows/test_control_resources_bases_contacts.py
=> Import des données de modalités de contact et de zones d'intervention des unités

frontend/cypress/e2e/side_window/mission/create_mission.spec.ts, frontend/src/features/missions/MissionForm/MissionForm.tsx
- je passais `isClosed` à `true` encas d'enregistrement "simple" ...
=> [Mission] Résolution d'un bug à l'enregistrement d'une mission

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/GetLegacyControlUnits.kt
=> [HOTFIX] Exclut les moyens archivés des unités legacy

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/cypress/e2e/utils/customDayjs.ts, frontend/cypress/e2e/utils/expectPathToBe.ts, frontend/cypress/e2e/utils/getLastIdFromCollection.ts, frontend/cypress/e2e/utils/getUtcDateInMultipleFormats.ts, frontend/src/domain/entities/dateRange.ts, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/features/missions/MissionsList/Filters/FilterTags.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
=> [Hotfix] Fixe la sélection de période sur la liste des unités

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts
=> [Tech] Fixe le test e2e du filtre de sélection depuis un mois dans la liste des missions

frontend/src/api/api.ts
=> [Hotfix] Fixe l'erreur d'ouverture de fiche des couches règlementaires

frontend/src/domain/entities/__tests__/getMissionStatus.test.ts, frontend/src/domain/entities/missions.ts
=> [Hotfix] Problème avec le statut de mission "terminée"

frontend/package-lock.json, frontend/package.json, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
=> [Unités] Amélioration de la recherche des unités depuis une mission

frontend/src/domain/shared_slices/Global.ts, frontend/src/features/Station/components/StationLayer/index.ts, frontend/src/features/Station/components/StationLayer/utils.ts, frontend/src/features/map/layers/Reportings/EditingReportingLayer.tsx, frontend/src/features/map/layers/Reportings/SelectedReporting.tsx, frontend/src/features/map/layers/Reportings/index.tsx, frontend/src/features/map/layers/Reportings/style.ts, frontend/src/features/map/layers/Semaphores/index.ts, frontend/src/features/map/layers/Semaphores/style.ts, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/reportings/ReportingCard.tsx, frontend/src/features/map/overlays/semaphores/SemaphoreCard.tsx
=> [Carte] Résolution des conflits avec la ligne pointillée des sémaphores + ajout des cette ligne sur les bases et signalements

.github/dependabot.yml
=> [Tech] Change la fréquence des updates Dependabot au mensuel

frontend/package-lock.json, frontend/package.json, frontend/src/domain/entities/controlUnit.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/FormikNameSelect.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/constants.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/utils.ts, frontend/src/utils/__tests__/sortCollectionByLocalizedProps.test.ts, frontend/src/utils/sortCollectionByLocalizedProps.ts
=> [Unités] Retouches diverses sur le backoffice et la fiche unité

frontend/src/features/layersSelector/search/LayerFilters.tsx, frontend/src/features/map/BaseMap.tsx, frontend/src/features/map/layers/Regulatory/index.ts, frontend/src/store/index.ts, frontend/src/store/reducers.ts
=> [ZonesRéglementaires] Résolution du bug au clique sur une zone réglementaire (sur la carte)

frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx, frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx
=> [Zones] Résolution du bug d'affichage de la carte (superposition d'éléments)

frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts, frontend/src/domain/use_cases/reporting/duplicateReporting.ts, frontend/src/domain/use_cases/reporting/editReportingInLocalStore.ts
=> [Mission] Invalidation du cache

frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
=> [Unité] Amélioration de la recherche des unités (vue liste et fiche mission)

.github/workflows/cicd-app.yml, Makefile, frontend/package-lock.json, frontend/package.json, frontend/src/api/APIWorker.ts, frontend/src/features/Reportings/ReportingForm/FormComponents/Source.tsx, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/map/controls/MapCoordinatesBox.tsx, frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts, frontend/src/features/map/layers/InterestPointLayer.tsx, frontend/src/features/map/layers/MapLayer.tsx, frontend/src/features/map/layers/MeasurementLayer.tsx, frontend/src/features/map/layers/Regulatory/RegulatoryPreviewLayer.ts, frontend/src/features/map/overlays/InterestPointOverlay.js, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, infra/docker/app/Dockerfile
=> [Tech] Migre Node de v18 vers v20

frontend/package-lock.json, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/features/MainWindow/components/RightMenu/ButtonWrapper.tsx, frontend/src/features/MainWindow/components/RightMenu/ControlUnitListButton.tsx, frontend/src/features/Reportings/Layers/MissionToAttach/index.tsx, frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx, frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx, frontend/src/features/Reportings/ReportingForm/FormContent.tsx, frontend/src/features/Reportings/ReportingsButton/index.tsx, frontend/src/features/Semaphores/SearchSemaphoreButton/index.tsx, frontend/src/features/Station/components/StationLayer/index.ts, frontend/src/features/Station/components/StationOverlay/StationCard/index.tsx, frontend/src/features/map/layers/Reportings/EditingReportingLayer.tsx, frontend/src/features/map/layers/Semaphores/index.ts, frontend/src/features/map/overlays/reportings/ReportingCard.tsx, frontend/src/features/map/overlays/semaphores/SemaphoreCard.tsx, frontend/src/features/map/tools/interestPoint/InterestPointMapButton.tsx, frontend/src/features/map/tools/measurements/MeasurementMapButton.tsx, frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx, frontend/src/features/missions/MissionForm/AttachReporting/index.tsx, frontend/src/features/missions/MissionsButton/index.tsx
- Resolve #944 
- Resolve #827
=> [Signalements] Différentes corrections sur le rattachement d'un signalement à une mission

frontend/src/api/missionsAPI.ts, frontend/src/domain/entities/missions.ts, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/domain/use_cases/reporting/attachMission.ts, frontend/src/domain/use_cases/reporting/closeReporting.ts, frontend/src/domain/use_cases/reporting/duplicateReporting.ts, frontend/src/domain/use_cases/reporting/editReportingInLocalStore.ts, frontend/src/domain/use_cases/reporting/switchReporting.ts, frontend/src/domain/use_cases/reporting/unattachMissionFromReporting.ts, frontend/src/features/Reportings/ReportingForm/AttachMission/AttachMissionToReportingModal.tsx, frontend/src/features/Reportings/ReportingForm/index.tsx, frontend/src/features/Reportings/slice.ts, frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx, frontend/src/features/missions/Missions.helpers.ts
=> [Mission] Résolution du souci de cache en cas de détachement d'un signalement depuis une mission

frontend/src/features/SideWindow/SideWindowLauncher.tsx, frontend/src/features/SideWindow/index.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
=> [SideWindow] Résolution du bug d'affiche de la side window lors de la première ouverture

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMissions.kt
Petit fix après avoir mergé une suggestion sans vérifier -_-
----
=> fix(GetMissions): use correct var

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/EnvActionNoteEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/EnvActionNoteProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/EnvActionMapper.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/missions/MissionEnvActionDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/missions/MissionEnvActionControlDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/missions/MissionEnvActionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/missions/MissionEnvActionNoteDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/missions/MissionEnvActionSurveillanceDataOutput.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/inputs/missions/CreateOrUpdateMissionDataInputUTests.kt, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/ActionForm/NoteForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/Missions.helpers.ts
=> [Mission] Résolution du bug d'enregistrement d'une note libre

README.md, backend/src/main/resources/log4j2-spring.xml, infra/configurations/backend/application-dev.properties
rotation every day
same systemoutput logger for every env
fix rotation dir
=> [Tech] fix env for development

backend/src/main/resources/db/migration/internal/V0.104__update_materialized_view_themes.sql
=> [Thématiques Plans de contrôle] mise à jour de la vue pour analyses sur metabase

frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/src/features/missions/Missions.helpers.ts
=> [Mission] Résolution du bug de la date de surveillance identique à la date de mission

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/entities/controlPlan.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ActionTheme.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/MultipleThemeElement.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/SurveillanceThemes.tsx, frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx, frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts
=> [Thématiques] Mise à jour des thématiques quand l'année de mission change (et pas de date d'action saisie)

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts, frontend/src/App.tsx, frontend/src/domain/entities/reporting.ts, frontend/src/features/Reportings/ReportingForm/FormComponents/Footer.tsx, frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/index.tsx, frontend/src/features/Reportings/ReportingForm/FormComponents/Validity.tsx, frontend/src/features/Reportings/ReportingForm/FormContent.tsx, frontend/src/features/Reportings/ReportingForm/Schema/index.tsx, frontend/src/features/Reportings/ReportingForm/formikUseCases/updateReportingThemes.ts, frontend/src/features/Reportings/style.ts, frontend/src/features/SideWindow/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/Validity.tsx, frontend/src/typings/index.d.ts
- Resolve #1040
Emplacement validé avec Adeline : 
----
=> [Signalement] Ajout du champ date

backend/src/main/resources/db/migration/internal/V0.107__update_reportings_sequence.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt.kt, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts
=> [Reporting] Résolution du bug d'enregistrement d'un signalement

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts, frontend/cypress/e2e/side_window/mission_form/close_mission_validation.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/src/domain/use_cases/reporting/unattachMissionFromReporting.ts, frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx, frontend/src/features/map/draw/DrawModal.tsx, frontend/src/features/map/layers/Reportings/index.tsx
=> [Reporting] Résolution du bug empêchant de rattacher plusieurs signalements à une mission

backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/FormikNameSelect.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/shared/TextareaForm.tsx
=> [Unités] Fixe plusieurs glitchs sur la fiche unité

frontend/src/domain/use_cases/missions/addMission.ts, frontend/src/domain/use_cases/reporting/createMissionFromReporting.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx
=> [Unités] Pouvoir créer une mission à partir d'une unité

backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt, frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Placeholder.tsx, frontend/src/features/Station/components/StationLayer/utils.ts, frontend/src/features/Station/components/StationOverlay/index.tsx, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/actions/index.tsx, frontend/src/features/missions/Overlays/ReportingToAttach/index.tsx
- Resolve #1105
- Resolve #1102
----
=> [Unités] Fixe quelques glitchs sur les bases

backend/src/main/resources/db/migration/internal/V0.108__update_public_schema_privileges.sql
=> Révocation des droits en modification pour tous les utilisateurs sur le schéma `public`

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/package-lock.json, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ActionTheme.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/MultipleThemeElement.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/TagsSelector.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx, frontend/src/hooks/useGetControlPlans.ts, frontend/src/hooks/useGetControlPlansByYear.ts, frontend/src/utils/sortControlPlans.ts
-  #755
Traitement des retours d'Adeline (ICI: https://github.com/MTES-MCT/monitorenv/issues/755#issuecomment-1863138146), excepté le 3ème point sur les filtres dans la vue liste des missions et signalements
----
=> [Thématiques] Traitement des retours design

infra/docker/app/Dockerfile
=> [Tech] Fixe Sentry CLI dans le build Docker

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt, backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql, frontend/cypress/e2e/side_window/reporting/filters.spec.ts, frontend/src/features/Reportings/Filters/Table/FilterTags.tsx, frontend/src/features/Reportings/ReportingForm/AttachMission/AttachedMissionCard.tsx, frontend/src/features/Reportings/ReportingsList/Cells/CellTarget.tsx, frontend/src/features/Reportings/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts, frontend/src/features/Reportings/utils.test.ts, frontend/src/features/Reportings/utils.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx
- Petits fixs UI
- Ajout de la possibilité de rechercher dans le champ description (modification requête back) via l'input de recherche par cible
- Resolve #1043
- Resolve #1118
- Resolve #1041 
- Resolve #1042
- Resolve #755
----
=> [Signalements] Plusieurs améliorations design

frontend/cypress/e2e/main_window/control_unit_list_dialog/filters.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/utils.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/FilterBar.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/types.ts, frontend/src/features/ControlUnit/components/ControlUnitListDialog/utils.ts, frontend/src/features/ControlUnit/utils.ts
=> [Unités] Améliorer recherche dans le module Unités de contrôle

.github/workflows/cicd-app.yml
=> [Tech] Augmente le nombre de jobs Cypress dans la CI

datascience/src/pipeline/flows/semaphores.py, datascience/src/pipeline/queries/cross/regulations.sql, datascience/src/pipeline/queries/cross/regulations_hashes.sql
=> [Pipeline] Fix synchro des sémaphores et des couches reg

frontend/cypress/e2e/main_window/interest_point.spec.ts, frontend/package-lock.json, frontend/src/api/missionsAPI.ts, frontend/src/features/Reportings/Layers/MissionToAttach/SelectedMissionToAttachLayer.tsx, frontend/src/features/Reportings/Layers/MissionToAttach/index.tsx, frontend/src/features/map/layers/Missions/SelectedMissionLayer.ts, frontend/src/features/missions/Layers/ReportingToAttach/index.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx
- Resolve #1181
- Resolve #1119
----
=> [Tech] Réduction des appels api à l'ouverture de l'application

.github/workflows/cicd-app.yml, .github/workflows/cicd-datapipeline.yml, .github/workflows/trivy.yml
=> [Tech] Restaure l'ancienne action pour Get last release version in CI

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/CanDeleteMissionResponse.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CanDeleteMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/DeleteMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/Missions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v1/missions/Missions.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CanDeleteMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/DeleteMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsITests.kt, frontend/cypress/e2e/back_office/control_unit_form.spec.ts, frontend/cypress/e2e/constants.ts, frontend/cypress/e2e/side_window/mission_form/delete_mission.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/utils/createMissionWithAttachedReportingAndAttachedAction.ts, frontend/cypress/e2e/utils/visitSideWindow.ts, frontend/src/api/missionsAPI.ts, frontend/src/features/Reportings/ReportingForm/AttachMission/index.tsx, frontend/src/features/map/layers/Missions/missions.style.ts, frontend/src/features/missions/MissionForm/MissionForm.tsx
=> [Mission] Détacher les signalements rattachés à une mission lors de sa supression

frontend/config/jest.config.js
=> [Tech] Fixe les paths dans la config Jest

frontend/cypress/e2e/side_window/mission_form/close_mission_validation.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/AutoSaveTag.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx, frontend/src/utils/timeagoFrenchLocale.ts
=> [Mission] Affichage de la date de création et de modification dans le bandeau du bas du formulaire de mission

.github/workflows/cicd-app.yml, frontend/puppeteer/setup.ts
=> [Tech] Utilise Firefox plutôt que Chrome dans les tests Puppeteer

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx, frontend/src/features/missions/MissionForm/index.tsx
Suppression du message de mise à jour de mission en vue de la mise en prod de fix du 23/02/24
- Related #1159 
----
=> [Mission] Suppression du message de mise à jour de mission dans le bandeau du bas

.github/workflows/cicd-app.yml
=> Tech - Disable puppeteer

frontend/cypress/e2e/side_window/mission_form/close_mission_validation.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx
=> [Mission] Affichage du message de création et mise à jour de mission dans le bandeau du bas

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/domain/use_cases/missions/cancelCreateAndRedirectToFilteredList.ts, frontend/src/domain/use_cases/missions/deleteTab.ts, frontend/src/features/Reportings/index.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitWarningMessage.tsx, frontend/src/features/missions/MissionForm/index.tsx
=> [Mission] Ajout d'un fond blanc sur le formulaire lorsque le warning d'une unité déjà en cours de mission est visible

frontend/src/api/missionsAPI.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/Reportings/ReportingForm/AttachMission/AttachedMissionCard.tsx
=> [Signalement] Possibilité de cliquer sur la carte de la mission dans le formulaire de signalement pour ouvrir la fiche mission

backend/src/main/resources/db/migration/internal/V0.117__update_analytics_views_with_new_themes.sql
=> Suppression des doublons d'actions dans le vues `analytics`

frontend/cypress/e2e/side_window/mission_form/close_mission_validation.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/cypress/e2e/utils/createMissionWithAttachedReportingAndAttachedAction.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/commonComponents/TargetSelector/index.tsx, frontend/src/features/commonComponents/VehicleTypeSelector/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/NatinfSelector.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/RelevantCourtSelector.jsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/index.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx, frontend/src/features/missions/MissionForm/Schemas/Infraction.ts, frontend/src/features/missions/MultiPointPicker.tsx, frontend/src/features/missions/MultiZonePicker.tsx, frontend/src/utils/getDateAsLocalizedString.tsx
- Ajout de `isRequired` sur tous les champs obligatoires (dans les actions notamment)
- Retour en arrière sur l'affichage du wording `(UTC)` : je l'ai remis sur les champs mais pas dans la timeline + suppression de la phrase en bas
- Resolve #1242
----
=> [Mission] Amélioration du style du formulaire et ajout de l'astérisque sur tous les champs obligatoires (ouverture + clôture)

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/cypress/e2e/side_window/mission_list/missions.spec.ts, frontend/cypress/e2e/side_window/reporting/filters.spec.ts, frontend/src/components/CustomGlobalStyle.ts, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/index.tsx, frontend/src/features/Reportings/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx, frontend/src/hooks/useGetControlPlansByYear.ts
- Resolve #1205
- Resolve #1124
- Resolve #1206
----
=> [Thèmes] Amélioration des filtres thèmes et sous-thèmes dans les vues listes + Résolution du bug de tri des signalements pas thèmes

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/missions/MissionForm/CloseEditModal.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/MissionFormBottomBar.tsx, frontend/src/features/missions/MissionForm/Schemas/index.ts
=> [Mission] Mise à jour des pop-up lorsqu'on quitte une mission + champ contact plus obligatoire

frontend/src/features/Reportings/ReportingsList/Columns/index.tsx
Le tri que j'avais mis en place ne fonctionnait pas bien car on recevait des `undefined`, je passe maintenant un string vide
- Resolve #1206
----
=> [Reporting] Résolution du bug sur le tri des signalements par thématique

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/reporting/reportings.spec.ts, frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/Reportings/ReportingForm/FormComponents/ThemeSelector/index.tsx, frontend/src/features/Reportings/ReportingForm/Schema/index.tsx
=> [Signalement] Rendre les champs thématique et sous-thématiques bloquants pour la création d'un signalement

.github/dependabot.yml, frontend/package-lock.json, frontend/package.json, frontend/src/features/SideWindow/index.tsx, frontend/src/pages/HomePage.tsx
- Resolve #1312 (il suffisait de mettre à jour monitor-ui)
=> [Tech] Mise à jour de dépendances

backend/src/main/resources/db/migration/internal/V0.125__create_reporting_actions_view.sql
=> Création de la vue `reporting_actions`

backend/src/main/resources/db/migration/internal/V0.126__add_updated_column_in_reportings.sql, frontend/src/api/missionsAPI.ts, frontend/src/domain/use_cases/missions/editMissionInLocalStore.ts, frontend/src/domain/use_cases/missions/saveMission.ts
=> [Reporting] Fix migration d'ajout de date de modification d'un signalement

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitResourceModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/EnvActionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/use_cases/missions/saveMission.ts
Reverts MTES-MCT/monitorenv#1354
=> Revert "[Tech] Bump org.springframework.boot:spring-boot-starter-data-jpa from 3.1.4 to 3.2.5 in /backend"

backend/build.gradle.kts, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/ControllersExceptionHandler.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitResourceModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/EnvActionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/use_cases/missions/saveMission.ts
Reverts MTES-MCT/monitorenv#1366
=> Revert "Revert "[Tech] Bump org.springframework.boot:spring-boot-starter-data-jpa from 3.1.4 to 3.2.5 in /backend""

frontend/package-lock.json, frontend/package.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/index.tsx, frontend/src/features/MainWindow/components/BannerStack/Item.tsx, frontend/src/features/MainWindow/components/BannerStack/index.tsx
=> [Unités] Corrige styles et bannière dans le formulaire d'édition de contact

datascience/src/pipeline/flows/amp_cacem.py, datascience/src/pipeline/flows/amp_ofb.py, datascience/tests/test_pipeline/test_flows/test_amp_ofb.py
fix un problème de conversion + renommage des flows plus explicite
=> [AMP] fix flow d'import des amp depuis l'OFB

frontend/src/features/layersSelector/overlays/OverlayContent.tsx
=> [Couches AMP & Reg] fix affichage du nom complet de la couche au survol

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/CreateOrUpdateMissionDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionDataOutput.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiLegacyMissionsITests.kt, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/features/missions/MissionForm/constants.ts
=> [Tech] Suppression des propriétés `closedBy` et `isClosed`

datascience/src/pipeline/emails/templates/email_actions_to_units.jinja, datascience/src/pipeline/flows_config.py, datascience/tests/test_pipeline/test_flows/expected_rendered_email.html
- Resolve #1361
+ Programmation de l'envoi chaque semaine le lundi à 5:00.
=> Modifications du texte et de la fréquence d'envoi de l'email des contrôles aux unités

backend/src/main/resources/db/migration/internal/V0.129__add_plan_column_in_analytics_actions_table.sql
=> Ajouter d'une colonne `plan` dans la vue `analytics_actions`

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts
=> [Test] fix tests e2e

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/features/LocateOnMap/index.tsx, frontend/src/features/Reportings/ReportingForm/FormikSyncReportingFields.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionsForm.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/FormikSyncMissionFields.tsx, frontend/src/features/missions/MissionForm/index.tsx, frontend/src/features/missions/MissionsList/CellActionThemes.tsx
- Resolve #344 
- Resolve #56
- Resolve #436 
- Resolve #138
- Resolve #1407 
----
=> [Design] Améliorations UI

backend/src/main/resources/db/migration/internal/V0.130__create_reporting_actions_view.sql
=> Mise à jour de la vue `reporting_actions`

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_zone.spec.ts, frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/cypress/e2e/utils/createMissionWithAttachedReportingAndAttachedAction.ts, frontend/cypress/e2e/utils/createPendingMission.ts, frontend/cypress/e2e/utils/getFutureDate.ts
La fonction `createMissionWithAttachedReportingAndAttachedAction` mettait une date de fin de mission antérieure à aujourd'hui, la sauvegarde automatiques était donc désactivée.
=> [Test] Fix des tests e2e

.github/workflows/cicd-app.yml, infra/docker/app/Dockerfile
=> [Tech] Envoi des sourcemaps pour les images publiées uniquement

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/Reportings/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/ReportingsList/ReportingsTable.tsx, frontend/src/features/missions/MissionsList/Columns/index.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx
Mise à jour de monitor-ui et modification des tableaux pour être ISO avec la prod (j'ai retravaillé les tailles de colonnes notamment)
=> [UI] Mise à jour de monitor-ui

backend/src/main/resources/db/migration/internal/V0.132__add_infractions_in_analytics_actions_table.sql
=> Ajout des informations d'infractions dans la table `analytics_actions`

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/controlPlans/ControlPlanDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/controlPlans/ControlPlanSubThemeDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/controlPlans/ControlPlanTagDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/controlPlans/ControlPlanThemeDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v1/ControlPlans.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ControlPlansITests.kt, frontend/src/api/controlPlans.ts
=> [RAPPORT_NAV] Déplacer le endpoint des plans de contrôles vers les API publiques

frontend/package-lock.json, frontend/package.json, frontend/src/api/googlePlacesAPI/googlePlacesAPI.ts, frontend/src/domain/shared_slices/LayerSidebar.ts, frontend/src/domain/use_cases/map/updateMapInteractionListeners.ts, frontend/src/features/layersSelector/administrative/index.tsx, frontend/src/features/layersSelector/base/index.tsx, frontend/src/features/layersSelector/myAmps/index.tsx, frontend/src/features/layersSelector/myRegulatoryLayers/index.tsx, frontend/src/features/layersSelector/overlays/PinnedOverlay.tsx, frontend/src/features/layersSelector/overlays/index.tsx, frontend/src/features/layersSelector/search/SearchOnExtentExtraButtons.tsx, frontend/src/features/layersSelector/search/hooks/useSearchLayers.ts, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/map/layers/Missions/SelectedMissionLayer.ts, frontend/src/features/map/overlays/MeasurementOverlay.tsx, frontend/src/uiMonitor/ol-override.css
Détail dans le ticket de ce que j'ai fait
- Resolve #1445
----
=> [Carte] Divers améliorations UX

.github/dependabot.yml
=> [Tech] Groupe la MAJ Dependabot des dépendances hors majeures et sécurité

frontend/src/features/InterestPoint/components/EditInterestPoint.tsx
Demande d'Adeline
Resolve #1214 
----
=> [Point d'intérêt]: remise du zoom lors de la sauvegarde d'un point d'intérêt

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx
=> [INFRACTION]: Ajout du nom du navire et de sa taille à l'affichage des infractions

frontend/src/features/missions/MissionForm/hooks/useUpdateMissionZone.ts
=> [Mission] Résolution du bug de suppression de contrôle

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/config/RapportnavProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/rapportnav/APIRapportNavMissionActionsRepository.kt, backend/src/main/resources/application.properties, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/rapportnav/APIRapportNavActionsRepositoryITests.kt, infra/configurations/backend/application-integration.properties, infra/configurations/backend/application-prod.properties
Ajout d'un timeout et de logs  lors d'un appel à l'API RapportNav
=> [RAPPORT NAV]: Ajout d'un timeout lors d'un appel à l'API RapportNav

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/exceptions/BackendUsageErrorCode.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContact.kt, backend/src/main/resources/db/migration/internal/V0.136__update_contact_phone_remove_spaces.sql, backend/src/main/resources/db/testdata/V666.14__update_contact_phone_remove_spaces.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContactUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitContactRepositoryITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitRepositoryITests.kt, frontend/cypress/e2e/main_window/control_unit_dialog/contact_list.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FormikPhoneField.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/constants.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/index.tsx
- Resolve #1467
----
---
- Fix d'un bug d'affichage lors de la suppression d'une unité de contact
- Fix d'un bug de suppression d'un numéro de téléphone
- maj de tanstack/react-table
=> [Contact des unités de contrôle] Ajout de la validation et de l'affichage des numéros de téléphone 

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContact.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContactUTests.kt, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/index.tsx
=> [Contact des unités de contrôle]: Fix de la validation du téléphone et de la modification d'une adresse mail

frontend/package-lock.json, frontend/package.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FieldWithButton.tsx
=> [Contact des unités de contrôle]: Fix de l'alignement des inputs et des boutons quand le message d'erreur est long

backend/src/main/resources/db/migration/internal/V0.133__metabase_upload_schema.sql, backend/src/main/resources/db/migration/internal/V0.138__metabase_upload_schema.sql
=> Ajout d'un schema `metabase_uploads`

backend/src/main/resources/db/migration/internal/V0.139__update_reporting_actions_view.sql
=> Ajout de la colonne `is_infraction_proven` dans la vue `reporting_actions`

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetEngagedControlUnits.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetFullMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/Missions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v1/missions/LegacyMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetEngagedControlUnitsUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiLegacyMissionsITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/src/api/missionsAPI.ts, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/features/missions/MissionsList/Filters/index.tsx, frontend/src/features/missions/MissionsSearch.tsx, frontend/src/hooks/useGetFilteredMissionsQuery.ts
=> [Missions] Pouvoir rechercher une cible dans la vue liste des missions

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/App.tsx, frontend/src/components/CustomGlobalStyle.ts, frontend/src/features/Reportings/components/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/components/ReportingsList/ReportingsTable.tsx, frontend/src/features/missions/MissionsList/Columns/index.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/paths.ts, frontend/src/utils/isLegacyFirefox.ts
=> [SIDE WINDOW] Correction du scroll des tableaux

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/config/SecurityConfig.kt, frontend/src/App.tsx
=> [Tech] Résous le souci de CORS

frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/shared_slices/Global.ts, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/SelectAMPs.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/SelectRegulatoryAreas.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/DrawVigilanceArea.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Form.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Frequency.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/DrawVigilanceAreaLayer.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/EditingVigilanceAreaLayer.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/style.ts, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/vigilanceAreaGeometryHelper.ts, frontend/src/features/VigilanceArea/constants.ts, frontend/src/features/VigilanceArea/slice.ts, frontend/src/features/VigilanceArea/types.ts, frontend/src/features/VigilanceArea/useCases/addFeatureToDrawedFeature.ts, frontend/src/features/VigilanceArea/useCases/displayOrHideOtherLayers.ts, frontend/src/features/VigilanceArea/useCases/saveVigilanceArea.ts, frontend/src/features/layersSelector/overlays/OverlayContent.tsx, frontend/src/features/layersSelector/overlays/index.tsx, frontend/src/utils/getRegulatoryThemesAsOptions.ts
- Resolve #1531
- Resolve #1477 
----
=> [Zone de vigilance] Ajustements après revue design

frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/AMPItem.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/RegulatoryAreaItem.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/EditingVigilanceAreaLayer.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/SelectedVigilanceAreaLayer.tsx, frontend/src/features/layersSelector/overlays/OverlayContent.tsx
=> [Zone de Vigilance] Résolution du bug d'affichage des amp liés à une zone de vigilance sur la carte 

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/src/features/Reportings/components/ReportingsList/GroupActions.tsx, frontend/src/features/Reportings/components/ReportingsList/ReportingsTable.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/features/missions/MissionsSearch.tsx
- Resolve #1464 
- Resolve #1448 
----
=> [SIDE WINDOW]: alignement du scroll avec le tableau des missions et des signalements + wording de la recherche de cible

frontend/src/api/utils/setAuthorizationHeaders.ts
=> [Cerbère] Ajout d'une condition OIDC_ENABLED pour envoyer le token jwt

frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/EditingVigilanceAreaLayer.tsx, frontend/src/features/VigilanceArea/slice.ts, frontend/src/features/layersSelector/index.tsx, frontend/src/features/layersSelector/overlays/LayerEvents.tsx, frontend/src/features/layersSelector/overlays/OverlayContent.tsx, frontend/src/features/layersSelector/overlays/PinnedOverlay.tsx, frontend/src/features/layersSelector/overlays/index.tsx, frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx, frontend/src/features/layersSelector/search/ResultsList/ResultListLayerGroup.tsx, frontend/src/features/map/utils.ts
=> [VigilanceArea] "Nettoyer" le layer des Amp liées à une zone de vigilance

frontend/src/features/VigilanceArea/components/VigilanceAreaForm/index.tsx, frontend/src/features/VigilanceArea/slice.ts
=> [Zone de vigilance] Ouverture de la modal de confirmation si une zone de vigilance est en cours d'édition et qu'on veut en créer une nouvelle

frontend/src/features/missions/MissionForm/Schemas/Infraction.ts, frontend/src/features/missions/Missions.helpers.ts, frontend/src/features/missions/components/ControlInfractionsTags.tsx
=> [Infraction] ne pas rendre le champ bloquant pour cause de non réponse administrative + ajout des tags dans la timeline

Makefile, frontend/src/domain/entities/administrativeLayers.ts, frontend/src/domain/entities/layers/constants.ts, frontend/src/features/layersSelector/administrative/index.tsx, frontend/src/features/map/layers/styles/administrativeAndRegulatoryLayers.style.ts
=> [Couches Administratives] Ajout de la couche Marpol dans le front

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/envActionControl/infraction/AdministrativeResponseEnum.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/missions/EnvActionDataInputUTests.kt, frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionFormHeaderVehicle.tsx, frontend/src/features/missions/MissionForm/Schemas/Infraction.ts, frontend/src/features/missions/Missions.helpers.ts
=> [Infraction]: fix du nb d'infractions dans les tags et ajout de la réponse administrative 'Aucune'

frontend/package-lock.json, frontend/package.json
Je downgrade pour pouvoir faire la mep. il y a une régression dans la version 10.9.0, je suis en train de regarder
=> [Tech] Mise à jour de Monitor-ui

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts
=> [Signalements]: Fix des tests cypress

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/LocateOnMap/index.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/layersSelector/administrative/index.tsx, frontend/src/features/layersSelector/base/index.tsx, frontend/src/features/layersSelector/index.tsx, frontend/src/features/layersSelector/myAmps/MyAMPLayersList.tsx, frontend/src/features/layersSelector/myAmps/index.tsx, frontend/src/features/layersSelector/myRegulatoryLayers/MyRegulatoryLayersList.tsx, frontend/src/features/layersSelector/myRegulatoryLayers/index.tsx, frontend/src/features/layersSelector/myVigilanceAreas/index.tsx, frontend/src/features/layersSelector/search/SearchOnExtentExtraButtons.tsx, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/layersSelector/utils/LayerSelector.style.ts
Fix UI + résolution du bug au moment de la création des signalements
- Resolve #1526
=> [UI] Résolution des bugs liés à la mise à jour de Monitor-ui

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/EnvActionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/envActionSurveillance/AwarenessEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/envActionSurveillance/EnvActionSurveillanceEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/envActionSurveillance/EnvActionSurveillanceProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/EnvActionMapper.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/actions/AwarenessDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/actions/EnvActionDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/actions/AwarenessDataOuput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/actions/EnvActionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/actions/EnvActionSurveillanceDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/missions/MissionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionEnvActionDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/outputs/MissionEnvActionSurveillanceDataOutput.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/actions/fixtures/EnvActionFixture.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrPatchEnvActionsUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/missions/CreateOrUpdateMissionDataInputUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/missions/EnvActionDataInputUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/Awareness.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/index.tsx, frontend/src/features/missions/MissionForm/Schemas/Surveillance.ts, frontend/src/features/missions/MissionForm/hooks/useUpdateSurveillance.ts
=> [Surveillance] Ajout des champs sensibilisation

frontend/package-lock.json, frontend/package.json, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Source.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/layersSelector/search/SearchOnExtentExtraButtons.tsx, frontend/src/features/missions/MissionsList/CellEditMission.tsx, frontend/src/features/missions/MissionsList/CellLocalizeMission.tsx
Correction de la clé de la liste des sources de signalements : 
- Bug lorsqu'on en ajoute plusieurs sémaphores ou unité sans en saisir un dans la liste.
----
=> [Monitor-UI & signalement] mise à jour & correction sur les sources de signalements

frontend/cypress/e2e/main_window/control_unit_dialog/contact_list.spec.ts, frontend/cypress/e2e/main_window/layerTree/vigilance_area_layers.spec.ts, frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx
=> [CONTROL_UNIT] Permettre de voir la liste des missions d'une unité et leur mission en cours

frontend/src/features/map/layers/styles/administrativeAndRegulatoryLayers.style.ts
=> [Zone administrative] Centrer le texte des zones de compétences des CROSS

frontend/src/features/Reportings/components/ReportingForm/FormComponents/Source.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx
Et de la couleur du séparateur entre source
----
=> [Signalement] Révision de la taille des marges 

frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/SelectAMPs.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/SelectRegulatoryAreas.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/DrawVigilanceArea.tsx, frontend/src/features/commonComponents/ZonePicker/index.tsx, frontend/src/features/layersSelector/myVigilanceAreas/MyVigilanceAreaLayerZone.tsx, frontend/src/features/layersSelector/myVigilanceAreas/index.tsx, frontend/src/features/layersSelector/search/ResultsList/index.tsx
=> [Zone de vigilance] Améliorations UI

frontend/src/features/Reportings/Filters/Map/index.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/index.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
=> [Mission & Signalement] Correction des filtres lorsqu'on réinitialise les filtres puis on recherche par période

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/ThemeSelector/index.tsx, frontend/src/features/Reportings/components/ReportingForm/Header.tsx, frontend/src/features/commonComponents/VesselTypeSelector/index.tsx
- Resolve #1515 
- Resolve #1582 
----
=> [Signalement] Ajout d'un message pour remplir les informations de la cible et possibilité de supprimer le type de véhicule saisi

frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/domain/shared_slices/ReportingsFilters.ts, frontend/src/features/Reportings/Filters/ReportingSearch.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/index.tsx, frontend/src/features/Reportings/Filters/style.ts, frontend/src/features/Reportings/components/ReportingsList/Cells/ButtonsRowGroup.tsx, frontend/src/features/Reportings/components/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/components/ReportingsList/GroupActions.tsx, frontend/src/features/Reportings/components/ReportingsList/ReportingsTable.tsx, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts, frontend/src/features/commonComponents/ReinitializeFiltersButton.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx, frontend/src/features/missions/MissionsSearch.tsx, frontend/src/hooks/useGetFilteredMissionsQuery.ts
=> [UI] Résolution des soucis de style sur les tableaux de missions et signalements

frontend/src/domain/entities/layers/constants.ts, frontend/src/features/Reportings/components/ReportingLayer/MissionToAttach/SelectedMissionToAttachLayer.tsx, frontend/src/features/Reportings/components/ReportingLayer/Reporting/EditingReportingLayer.tsx, frontend/src/features/Reportings/components/ReportingLayer/Reporting/SelectedReporting.tsx, frontend/src/features/Reportings/components/ReportingLayer/Reporting/style.ts, frontend/src/features/map/layers/Missions/EditingMissionLayer.ts, frontend/src/features/map/layers/Missions/SelectedMissionLayer.ts, frontend/src/features/map/layers/Missions/missions.style.ts, frontend/src/features/map/layers/utils.test.ts, frontend/src/features/map/layers/utils.ts
J'ai également fait le changement pour les signalements même si ce n'était pas demandé.
- Resolve #1588 
----
=> [Missions & Signalements] Modifier le comportement d'affichage de la zone de mission au survol

frontend/package-lock.json, frontend/package.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FieldWithButton.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/FormikNameSelect.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Form/index.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Form.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/shared/TextareaForm.tsx
=> [Fiche Unité] Améliorations UI

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ReportingModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBReportingRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepositoryITests.kt, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts
Mission : 
~250 requetes -> ~10 requetes
Signalements : 
~90 requetes -> ~25 requetes
- Resolve #1547
=> [Perf] [Mission & Signalement] Réécriture des requêtes de recherche

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/EnvActionNoteEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/EnvActionNoteProperties.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/EnvActionMapper.kt, backend/src/main/resources/db/migration/internal/V0.150__update_note_completion_status.sql
=> [Action Note] Mettre le statut complété pour les actions de type "NOTE"

frontend/package-lock.json, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/style.ts, frontend/src/features/Reportings/components/ReportingsList/Cells/ButtonsRowGroup.tsx, frontend/src/features/Reportings/components/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/components/ReportingsList/GroupActions.tsx, frontend/src/features/Reportings/components/ReportingsList/index.tsx, frontend/src/features/missions/MissionsList/Filters/FilterTags.tsx, frontend/src/features/missions/MissionsList/index.tsx, frontend/src/features/missions/MissionsSearch.tsx
- Resolve #1657 
- Resolve #1651 
----
=> [UI] Améliorations UI

frontend/package-lock.json, frontend/public/Cursor_border.svg, frontend/src/components/CustomGlobalStyle.ts, frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/shared_slices/Map.ts, frontend/src/domain/use_cases/map/closeAreaOverlay.ts, frontend/src/domain/use_cases/map/closeLayerListPopUp.ts, frontend/src/domain/use_cases/map/updateMapInteractionListeners.ts, frontend/src/features/InterestPoint/components/InterestPointLayer.tsx, frontend/src/features/InterestPoint/components/InterestPointOverlay.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/SelectAMPs.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/SelectRegulatoryAreas.tsx, frontend/src/features/VigilanceArea/useCases/displayOrHideOtherLayers.ts, frontend/src/features/layersSelector/overlays/LayerEvents.tsx, frontend/src/features/layersSelector/overlays/OverlayContent.tsx, frontend/src/features/layersSelector/overlays/OverlayPositionOnCoordinate.tsx, frontend/src/features/layersSelector/overlays/PinnedOverlay.tsx, frontend/src/features/layersSelector/overlays/style.ts, frontend/src/features/layersSelector/search/ResultsList/AMPLayerGroup/AMPLayer.tsx, frontend/src/features/layersSelector/search/ResultsList/RegulatoryLayerGroup/RegulatoryLayer.tsx, frontend/src/features/layersSelector/search/ResultsList/VigilanceAreaLayer/index.tsx, frontend/src/features/layersSelector/search/SearchOnExtentExtraButtons.tsx, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/hooks/useMoveOverlayWhenDragging.ts
=> [Carte] Possibilité de bouger la pop-up de liste des zones reg, AMP et zone de vigilance

frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx
=> [Zone de Vigilance] Ajout de la récurrence dans la fiche de consultation

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/features/layersSelector/myAmps/MyAMPLayerGroup.tsx, frontend/src/features/layersSelector/myAmps/MyAMPLayersList.tsx, frontend/src/features/layersSelector/myRegulatoryLayers/MyRegulatoryLayerGroup.tsx, frontend/src/features/layersSelector/myRegulatoryLayers/MyRegulatoryLayersList.tsx, package-lock.json
- Resolve #1677 
- Resolve #1683 
----
=> [Map] Adapter la taille de la fenêtre des AMP et zone reg épinglées + Filtres de mission à "Aujourd'hui" par défaut

backend/src/main/resources/db/migration/internal/V0.152__migration_poseidon_infraction.sql
=> [Infractions] Générer des id sur les infractions provenant de poseidon

frontend/cypress/e2e/main_window/vigilance_area/create_vigilance_area.spec.ts
=> [Tech] Résolution du bug sur le test e2e de création de zone de vigilance

.github/workflows/cicd-app.yml, frontend/package-lock.json
Mise à jour de codecov qui n'était plus maintenu pour utiliser la dernière version
=> [Tech] Mise à jour de codecov

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaEnvActionRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/actions/fixtures/EnvActionFixture.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaEnvActionRepositoryITest.kt
=> [EnvAction] La sauvegarde doit conserver les plans de controle

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContact.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/controlUnit/CreateOrUpdateControlUnitContactUTests.kt
=> [Contact Unité] Garantir l'unicité de l'adresse email de diffusion lors de la création d'un nouveau contact

frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitContactList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/index.tsx, frontend/src/features/ControlUnit/utils.ts, frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/Item.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/ContactDetails.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/ControlUnitAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/Details.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/InterventionAreaDetails.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/ResourcesDetails.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/style.ts, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/SelectedAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/index.tsx, frontend/src/features/Dashboard/slice.ts
=> [Tableau de bord & Brief] Ajout du bloc "Unités"

frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Filters/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Panel/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/index.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Form.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/style.ts, frontend/src/features/layersSelector/search/index.tsx, frontend/src/utils/getAmpsAsOptions.ts, frontend/src/utils/getRegulatoryThemesAsOptions.ts
=> [Tableau de bord & Brief] Ajout des filtres sur la vue Tableau de bord

frontend/package-lock.json, frontend/src/features/Dashboard/components/DashboardsNavBar.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/useCases/createDashboard.ts, frontend/src/hooks/useEscapeKey.ts
=> [Tableau de bord & Brief] Ajout du nom du dashboard et possibilité de le modifier dans l'onglet

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/reportings/SSEReporting.kt, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/PreviewVigilanceAreasLayer.tsx, frontend/src/features/map/index.tsx, frontend/src/features/map/layers/AMP/AMPPreviewLayer.ts, frontend/src/features/map/layers/AMP/index.ts, frontend/src/features/map/layers/Regulatory/RegulatoryPreviewLayer.ts, frontend/src/features/map/layers/Regulatory/index.ts, frontend/src/features/map/layers/SearchExtentLayer.tsx
=> [Couches carto] Résolution du bug des couches qui n'apparaissent pas sur la carte

frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/TerritorialPressure/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/index.tsx
=> [Tableau de bord & Brief] Résolution du bug du tooltip et des filtres des Unités

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/dashboard/DashboardEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/dashboard/SaveDashboard.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/dashboards/DashboardDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/DashboardModel.kt, backend/src/main/resources/db/migration/internal/V0.155__add_column_facade_to_dashboard.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/dashboard/SaveDashboardUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/dashboard/fixtures/DashboardFixture.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaDashboardRepositoryITest.kt
=> [Tableau de bord] Ajout au calcul de la facade

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_dates_validation.spec.ts, frontend/cypress/e2e/side_window/reporting/create_reporting.spec.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/Reportings/components/ReportingForm/FormComponents/ThemeSelector/index.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/Reportings/components/ReportingForm/formikUseCases/updateReportingThemes.ts, frontend/src/features/missions/MissionForm/ActionForm/Themes/ActionTheme.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts, frontend/src/hooks/useGetControlPlansByYear.ts
=> [Thématiques] Pouvoir sélectionner une sous-thématique avant une thématique (missions et signalements)

frontend/public/icons/Bullseye.svg, frontend/src/api/dashboardsAPI.ts, frontend/src/domain/entities/layers/constants.ts, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/ControlUnitAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx, frontend/src/features/Dashboard/components/DashboardsList/Columns/index.tsx, frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/components/Layers/DashboardsLayer.tsx, frontend/src/features/Dashboard/components/Layers/SelectedDashboardLayer.tsx, frontend/src/features/Dashboard/components/Overlays/DashboardCard.tsx, frontend/src/features/Dashboard/components/Overlays/DashboardOverlay.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/types.ts, frontend/src/features/Dashboard/useCases/closeTab.ts, frontend/src/features/Dashboard/useCases/drawFeature.ts, frontend/src/features/Dashboard/useCases/editDashboard.ts, frontend/src/features/Dashboard/useCases/selectDashboardOnMap.ts, frontend/src/features/Reportings/components/ReportingLayer/Reporting/style.ts, frontend/src/features/Semaphore/components/Layer/style.ts, frontend/src/features/Station/components/StationLayer/utils.ts, frontend/src/features/layersSelector/overlays/LayerEvents.tsx, frontend/src/features/layersSelector/overlays/style.ts, frontend/src/features/map/index.tsx, frontend/src/features/map/layers/Dashboards/SelectedDashboardLayer.tsx, frontend/src/features/map/layers/Dashboards/index.tsx, frontend/src/features/map/layers/Missions/missions.style.ts, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/style.ts
=> [Tableau de bord] Ajout des dashboards sur la carte

frontend/cypress/e2e/main_window/layerTree/vigilance_area_layers.spec.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx
=> [Thématiques] Amélioration de la recherche des sous-thématiques

frontend/src/features/VigilanceArea/components/VigilanceAreasList/Columns/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Filters/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/FrequencyCell.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/HighlightCell.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/VigilanceAreasTable.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/index.tsx
=> [Zones de Vigilance] Corrections filtres - vue liste

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/src/domain/entities/dateRange.ts, frontend/src/features/map/layers/Missions/index.tsx, frontend/src/features/map/layers/Missions/missionGeometryHelpers.ts, frontend/src/features/map/layers/Missions/missions.style.ts, frontend/src/features/missions/MissionsList/index.tsx, frontend/src/features/missions/hooks/useGetFilteredMissionsQuery.ts
- Suppression des cercles représentant les contrôles
- Ajout d'un trait entre les contrôles et la mission
- Resolve #1404
- Resolve #1804 
----
=> [Mission] Ajout d'une ligne entre la mission et les contrôles et suppression des cercles pour les contrôles + Ajout d'un filtre Année en cours

backend/src/main/resources/db/migration/internal/V0.159__fix_reportings_sources_emptied.sql, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/Reportings/components/ReportingForm/Schema/index.tsx, frontend/src/features/Reportings/components/ReportingsList/Columns/index.tsx
=> [Source de signalement] Migration de récupération de données et ajout d'un contournement au cas où il n'y pas de sources

.github/dependabot.yml
=> [Tech] Supprime Ivan des assigné.es dans la config Dependabot

backend/src/main/resources/db/testdata/V666.08__add_control_plan_2025.sql, backend/src/main/resources/db/testdata/V666.10__insert_dummy_env_actions.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlPlanSubThemeRepositoryITests.kt, frontend/cypress/e2e/main_window/measurements_tools.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/reporting/filters.spec.ts, frontend/src/features/map/layers/MeasurementLayer.tsx
=> [Map] Résolution du bug sur les outils de mesure de la carto

frontend/src/domain/entities/layers/constants.ts, frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/components/Layers/DashboardsLayer.tsx, frontend/src/features/layersSelector/overlays/LayerEvents.tsx, frontend/src/features/layersSelector/overlays/OverlayPositionOnCoordinate.tsx
-  traitements de retours : https://github.com/MTES-MCT/monitorenv/issues/1806#issuecomment-2462792335
----
=> [Tableau de bord & Brief] Améliorations UX

frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Bookmark/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/FirstColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/SecondColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/ThirdColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/style.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/utils.ts, frontend/src/features/Dashboard/components/DashboardForm/Comments/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/TerritorialPressure/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Weather/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/slice.ts, frontend/src/features/Dashboard/components/DashboardForm/useObserver.tsx, frontend/src/features/SideWindow/index.tsx
=> [Tableau de bord] Ajout des ancres et retour aux sections

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/reportings/AbstractReportingModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/reportings/ReportingModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/reportings/ReportingModelJpa.kt
=> [Signalement] Corriger la duplication des sources de signalements dans la vue liste

frontend/src/api/api.ts, frontend/src/api/dashboardsAPI.ts, frontend/src/api/reportingsAPI.ts, frontend/src/api/vigilanceAreasAPI.ts, frontend/src/features/Dashboard/components/DashboardForm/Amps/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Layer.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/useCases/closeTab.ts, frontend/src/features/Dashboard/useCases/editDashboard.ts, frontend/src/features/SideWindow/SideWindowLauncher.tsx, frontend/src/pages/HomePage.tsx
=> [Tableau de bord] revue UX 

frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/EditCell.tsx
=> [Zone de vigilance] Afficher la fenêtre de confirmation si on édite une ZV depuis la vue liste et qu'une autre est en cours d'édition

frontend/src/features/Dashboard/components/DashboardForm/Comments/index.tsx, frontend/src/features/Dashboard/components/Pdf/Comments/index.tsx, frontend/src/features/Dashboard/components/Pdf/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/Reportings/index.tsx
* Cacher la légende des signalements si aucun n'est sélectionné
* Fix du debounce des commentaires
* Mettre le bouton de génération de brief en disabled lors du chargement avec un autre message
- Resolve #1788
----
=> [Tableau de bord & Brief] Ajout d'un feedback sur le bouton de génération de brief

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/envAction/envActionControl/infraction/SeizureTypeEnum.kt, backend/src/main/resources/db/migration/internal/V0.166__update_default_seizure_in_infractions.sql, backend/src/main/resources/db/testdata/V666.10__insert_dummy_env_actions.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt, frontend/cypress/e2e/main_window/layerTree/vigilance_area_layers.spec.ts, frontend/src/domain/entities/missions.ts, frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/Columns/ThirdColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/SelectedAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardsList/Columns/index.tsx, frontend/src/features/Dashboard/components/DashboardsList/Rows/RegulatoryAreasThemesCell.tsx, frontend/src/features/commonComponents/Modals/MapInteraction.tsx, frontend/src/features/layersSelector/overlays/OverlayContent.tsx, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts, frontend/src/features/missions/Layers/missions.style.ts, frontend/src/features/missions/MissionForm/Schemas/Infraction.ts, frontend/src/features/missions/Missions.helpers.ts
- Résolution d'un bug sur la ligne enter mission et contrôle
- Résolution d'un bug sur le filtre "Période spécifique" des zones de vigilance
- Suppression des zooms vers les signalements et zones de vigilance lorsqu'on les épingle dans un tableau de bord
- Suppression de "Aucune" pour le champ Appréhension/saisie
- Ajout de la notion "En tout temps" pour les zones de vigilance sur la pop-up des couches
- Resolve #1759
- Resolve #1846
- Resolve #1875
----
=> [UX] Diverses corrections

frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Bookmark/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/Comments/index.tsx, frontend/src/features/commonComponents/Modals/MapInteraction.tsx
- Resolve #1807
- Resolve #1801
- Resolve #1925
=> [Tableau de bord] retour ui

frontend/src/api/reportingsAPI.ts
=> [Tableau de bord & Brief] Récupérer les signalements à jour dans les tableaux de bord

frontend/src/features/Dashboard/components/DashboardForm/Columns/FirstColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/TerritorialPressure/index.tsx
=> [Tableau de Bord & Brief] Utilisation des ids pour les lien Metabase des zones reg

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/Table/LocalizeCell.tsx, frontend/src/components/Table/PaddingForVirtualizeTable.tsx, frontend/src/components/Table/index.tsx, frontend/src/components/Table/style.ts, frontend/src/features/Dashboard/components/DashboardsList/DashboardsTable.tsx, frontend/src/features/Reportings/components/ReportingsList/ReportingsTable.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/VigilanceAreasTable.tsx, frontend/src/features/missions/MissionsList/CellEditMission.tsx, frontend/src/features/missions/MissionsList/Columns/index.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/hooks/useTableVirtualizer.ts, frontend/src/utils/getMissionTitle.ts
- Voir ici pour les modifications et l'ajout de ligne "vides" dans les tableaux: https://github.com/TanStack/virtual/discussions/476
- Ajout de id dans le formulaire + les onglets de navigation
- Modification de la vue liste pour l'adapter aux écran en 1920 px
- Resolve #1831
----
=> [Mission] Ajout de l'int dans la formulaire et les onglets + résolution du bug au scroll dans le tableau

frontend/src/features/Dashboard/useCases/filters/filterByUpdatedAt.ts
=> [Tableau de bord]: ne pas filtrer les tableaux quand il n'y a pas de date de mise à jour

frontend/src/components/Table/index.tsx, frontend/src/features/Dashboard/components/DashboardsList/Filters.tsx
=> [Tech] Fix de bugs html

backend/src/main/resources/db/migration/internal/V0.167__update_vigilance_areas_on_complete_year.sql, frontend/cypress/e2e/main_window/layerTree/search_zone.spec.ts, frontend/cypress/e2e/main_window/layerTree/vigilance_area_layers.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/layersSelector/search/LayerFilters.tsx, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
=> [Zones de vigilance] Résolution du bug sur le filtre date des zones de vigilances + Passage des ZV sur tout 2024 à "En tout temps"

frontend/src/features/ControlUnit/components/ControlUnitListDialog/slice.ts, frontend/src/features/ControlUnit/useCases/centerOnStation.ts, frontend/src/features/Mission/components/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx
=> [Mission] Réinitialiser les filtres des unités de contrôle au moment du zoom

frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/style.ts
=> [Tableau de bord & Brief] Résolution du bug d'affichage de la liste des AMP

frontend/cypress/e2e/side_window/dashboard_list/filters.spec.ts, frontend/src/features/Dashboard/components/DashboardsList/Columns/index.tsx, frontend/src/features/Dashboard/components/DashboardsList/Rows/RegulatoryAreasThemesCell.tsx
=> [Tableau de bord] Afficher les thématiques au lieu des zones réglementaires dans la vue liste

frontend/src/features/layersSelector/myVigilanceAreas/index.tsx
=> [Zones de vigilance] Ajout d'un bouton dans la section "Mes zones de vigilances" pour aller sur la vue liste

backend/src/main/resources/db/testdata/V666.12__insert_dummy_reportings.sql, frontend/cypress/e2e/side_window/reporting/reportings.spec.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx, frontend/src/features/Reportings/components/ReportingsList/Cells/ButtonsRowGroup.tsx, frontend/src/features/Reportings/useCases/archiveReporting.ts
=> [Signalement] Ne rendre accessible le bouton d'archivage que si le signalement est valide

backend/src/main/resources/db/testdata/V666.07__insert_dummy_control_units.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitRepositoryITests.kt, frontend/cypress/e2e/back_office/control_unit_table/filters.spec.ts, frontend/cypress/e2e/main_window/control_unit_list_dialog/filters.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/features/Mission/components/MissionForm/ActionForm/ControlForm/OtherControlTypesForm.tsx, frontend/src/features/Mission/components/MissionForm/hooks/useUpdateOtherControlTypes.ts
=> [Mission]  Ajout de la section "Autres contrôles effectués par l'unité" pour les ULAM

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionWithActionsAndAttachedReporting.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/CreateOrUpdateReporting.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceArea.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/validators/mission/MissionValidator.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/validators/mission/MissionValidatorUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/validators/reporting/ReportingValidatorUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/validators/vigilance_area/VigilanceAreaValidatorUTest.kt
=> [Mission] Suppression temporaire de la validation back

frontend/src/features/Dashboard/components/DashboardForm/Reportings/Filters.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Amps/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/v1/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/v1/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Reportings/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/style.ts, frontend/src/features/Dashboard/components/Pdf/v2/Amps/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/v2/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/v2/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Reportings/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/style.ts
- Resolve #2075
- Resolve #2074 
- Resolve #1991 
- Resolve #2062 (les deux derniers points qu'il manquait)
----
=> [Brief] Regroupement des couches sélectionnées par entité + Ajout du carré de couleur

frontend/src/features/Dashboard/components/Pdf/v1/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Table/index.tsx
=> [Brief] Retirer la taille maximale des cellules du tableau récapitulatif

frontend/src/features/Mission/components/MissionForm/Schemas/ControlPlans.ts
=> [Mission] Résolution du bug de mission qui ne s'enregistre pas

frontend/cypress/e2e/main_window/search_places.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/ControlForm/index.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/SurveillanceForm/index.tsx, frontend/src/features/Mission/components/MissionForm/ActionsTimeLine/ActionCard/EnvActions/index.tsx, frontend/src/features/Mission/components/MissionForm/ActionsTimeLine/index.tsx
=> [Mission] Résolution du bug de duplication d'action

frontend/src/features/Dashboard/hooks/useExportImages.tsx
Retour de christophe en séance
=> [Brief]: Zoom sur la zone du tableau de bord plutot que sur la taille maximale

frontend/src/features/Mission/components/MissionForm/hooks/useUpdateMissionZone.ts
=> [Mission] Recalculer la zone de mission si une action a été supprimée par le CSNP

frontend/src/features/Dashboard/components/DashboardForm/Footer/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Table/index.tsx, frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Brief] Amélioration du tableau récapitulatif des zones

frontend/src/features/Dashboard/components/Pdf/v1/Layout/Cover.tsx, frontend/src/features/Dashboard/components/Pdf/v1/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Layout/Cover.tsx, frontend/src/features/Dashboard/components/Pdf/v2/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/hooks/useExportImages.tsx
- Ajout des mentions lorsqu'il n'y a aucune sélection.
- Révision de typo
- Correction d'un alignement dans l'encadré des zones de vigilances.
- Resolve #1990
=> [Brief] : Révision du style de la page de garde

backend/src/main/resources/db/migration/internal/V0.174__add_default_value_to_dashboard_link.sql, frontend/src/features/Dashboard/components/Pdf/v1/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Brief.tsx
- Corrige également une condition d'affichage dans les briefs.
- Resolve #2009
=> [Tableau de bord] Correction des anciens tableaux de bord sans liens dans les pieces jointes

frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Brief] Modification de la résolution des images

frontend/src/features/Dashboard/components/Pdf/v1/Layout/Cover.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Reportings/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/style.ts, frontend/src/features/Dashboard/components/Pdf/v2/Amps/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Layout/Cover.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Reportings/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/style.ts
+ fix typo AMP => Aires Marines Protégées
- Resolve #1992
=> [Brief] Ajout de définitions 

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/recentActivity/InfractionEnum.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IEnvActionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/recentActivity/GetRecentControlsActivity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/inputs/recentActivity/RecentControlsActivityDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaEnvActionRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaEnvActionRepositoryITests.kt, frontend/cypress/e2e/main_window/recentActivity/filters.spec.ts, frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/types/layer.ts, frontend/src/features/RecentActivity/components/Layers/RecentControlsActivityLayer.tsx, frontend/src/features/RecentActivity/components/Layers/style.ts, frontend/src/features/RecentActivity/components/Overlays/RecentControlActivityOverlay.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/RecentActivityFilters.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/index.tsx, frontend/src/features/RecentActivity/slice.ts, frontend/src/features/RecentActivity/types.ts, frontend/src/features/map/index.tsx, frontend/src/features/map/overlays/actions/ControlCard.tsx, frontend/src/features/map/overlays/actions/index.tsx, frontend/src/store/reducers.ts
=> [Activité récente] Ajout des filtres sur l'interface + pop-up du contrôle au survol

frontend/src/components/Menu.tsx, frontend/src/features/RecentActivity/components/Layers/RecentControlsActivityLayer.tsx, frontend/src/features/RecentActivity/components/Layers/recentControlActivityGeometryHelper.ts, frontend/src/features/RecentActivity/components/Layers/style.ts, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/DistinctionFilters.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/RecentActivityFilters.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/index.tsx, frontend/src/features/RecentActivity/slice.ts, frontend/src/features/RecentActivity/types.ts
=> [Activité Récente] Ajout de l'encart pour distinguer les contrôles avec ou sans infraction

frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/components/Layers/style.ts, frontend/src/features/Dashboard/hooks/useExportImages.tsx, frontend/src/features/Reportings/components/ReportingLayer/Reporting/style.ts
=> [Tableau de bord & brief] Ajout des infos des signalements sur la vue globale du Brief

backend/build.gradle.kts, backend/gradle/wrapper/gradle-wrapper.properties, infra/docker/app/Dockerfile
- upgrade JVM compatibility from 17 to 21
- reorganize dependencies
----
=> tech: Montée de version de la JVM et nettoyage de dépendences

frontend/src/features/RecentActivity/components/Layers/style.ts, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/RecentActivityFilters.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/index.tsx
- Mise du vert des croix
- Largeur de la modale dynamique suivant si un filtre par zone géométrique est présent ou non
- Résolution d'un bug à la suppression d'une zone géométrique (si on en avait plusieurs de saisies)
- Resolve #2148 
- Resolve #2145 
----
=> [Activité Récente] Design review

frontend/src/domain/entities/layers/constants.ts, frontend/src/features/Dashboard/components/Pdf/v1/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/v2/GeneratePdfButton.tsx, frontend/src/features/Dashboard/hooks/useExportImages.tsx
Refacto hook
remove useEffect and useMemo to download pdf
=> [Brief]: Refonte technique du téléchargement du brief et de la récupération d'images

frontend/public/icons/dot.svg, frontend/src/features/RecentActivity/components/RecentActivityLegend.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/index.tsx, frontend/src/features/map/index.tsx
- Ajustement de la légende quand elle s'affiche en basede page pour être iso avec la maquette
- Mise à jour du svg pour qu'il soit de la bonne taille (30x30) et ainsi que les pastilles s'affichent de la bonne taille aussi
- Resolve #2176
- Resolve #2178 
----
=> [Activité Récente] Améliorations UI

frontend/src/features/RecentActivity/components/Layers/RecentActivityLayerEvents.tsx, frontend/src/features/RecentActivity/components/Overlays/OverlayContent.tsx, frontend/src/features/RecentActivity/components/Overlays/SelectedOverlay.tsx, frontend/src/features/RecentActivity/components/RecentActivityLegend.tsx, frontend/src/features/RecentActivity/useCases/selectFeaturesList.ts, frontend/src/features/layersSelector/overlays/LayerEvents.tsx
=> [Activité Récente] Amélioration de la liste des contrôles sur la carte

backend/src/main/resources/db/testdata/V666.15__insert_dummy_vigilance_area.sql, frontend/cypress/e2e/main_window/vigilance_area/edit_vigilance_area.spec.ts
Les tests sur les zones de vigilance ne passaient plus, j'ai mis à jour la date de fin de la zone de vigilance 7
=> [Tech] Mise à jour des données test des Zones de vigilance

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/monitorfish/APIFishMissionActionsRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/monitorfish/APIFishMissionActionsRepositoryITests.kt, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts
Le header `x-api-key` n'était plus envoyé
=> [Tech] résolution du bug d'appel à l'api Fish

frontend/cypress/e2e/main_window/layerTree/search_zone.spec.ts, frontend/cypress/e2e/main_window/layerTree/vigilance_area_layers.spec.ts, frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Tableau de Bord & Brief] Suppression du point au milieu de la zone du Brief

frontend/src/features/Dashboard/components/DashboardForm/Footer/CreateMailButton.tsx, frontend/src/features/Dashboard/components/DashboardForm/Footer/index.tsx, frontend/src/features/Dashboard/components/Pdf/GeneratePdfButton.tsx, frontend/src/features/Dashboard/hooks/useGenerateBrief.ts
=> [Tableau de Bord & Brief] Ajout d'un bouton pour générer le brief et ouvrir un mail pré-rempli

frontend/src/features/RecentActivity/components/Overlays/RecentActivityControlCard.tsx, frontend/src/features/commonComponents/ControlCard/index.tsx
=> [Activité Récente] Ajout du bouton pour ouvrir la mission depuis la pop-up de contrôle

frontend/src/features/Reportings/useCases/archiveReporting.ts, frontend/src/features/Reportings/useCases/reduceOrCollapseReportingForm.ts, frontend/src/features/Reportings/useCases/saveReporting.ts, frontend/src/features/map/draw/DrawModal.tsx
=> [Carte] Résolution du bug des boutons de droite qui ne sont pas à la bonne place

frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/DrawVigilanceAreaLayer.tsx
Une erreur a été introduite lors de la refacto faite dans ce ticket : https://github.com/MTES-MCT/monitorenv/pull/2156/
- Resolve #2229
----
=> [Zone de vigilance] Résolution du bug lors de la modification d'une zone déjà dessinée

frontend/src/features/Dashboard/components/DashboardForm/Footer/CreateMailButton.tsx, frontend/src/features/Dashboard/components/Pdf/GeneratePdfButton.tsx
Testé et validé en inté
- Resolve #2240
----
=> [Matomo] Ajout d'événements pour le téléchargement et le partage d'un brief

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/security/UserAuthorizationCheckFilter.kt
=> [Authentification] Résolution du bug à l'authentification

frontend/src/features/Dashboard/components/DashboardForm/Columns/FirstColumn.tsx, frontend/src/features/Dashboard/components/Pdf/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/Layout/Cover.tsx
=> [Tableau de bord & Brief] Déplacement des zones de vigilance pour qu'elles soient en haut du Tableau de bord et du Biref

frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/components/Layers/SelectedDashboardLayer.tsx, frontend/src/features/Dashboard/components/Pdf/Amps/index.tsx, frontend/src/features/Dashboard/components/Pdf/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/Layout/AreaImage.tsx, frontend/src/features/Dashboard/components/Pdf/Layout/AreaLink.tsx, frontend/src/features/Dashboard/components/Pdf/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/icons/ExternalLink.tsx, frontend/src/features/Dashboard/components/Pdf/style.ts, frontend/src/features/Dashboard/components/Pdf/utils.ts, frontend/src/features/Dashboard/hooks/useExportImages.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaLayer/style.ts, frontend/src/features/map/layers/AMP/AMPLayers.style.ts, frontend/src/features/map/layers/MeasurementLayer.tsx, frontend/src/features/map/layers/styles/administrativeAndRegulatoryLayers.style.ts, frontend/src/features/map/layers/styles/measurement.style.ts
=> [Brief] Ajout de la minicarte aux briefs

frontend/src/features/Dashboard/components/DashboardForm/DashboardRecentActivity/index.tsx, frontend/src/features/Dashboard/components/MapFocusForDashboardBanner.tsx, frontend/src/features/Dashboard/components/Pdf/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/RecentActivity/ControlUnitDetailsView.tsx, frontend/src/features/Dashboard/components/Pdf/RecentActivity/GlobalView.tsx, frontend/src/features/Dashboard/components/Pdf/RecentActivity/RecentActivityByUnit.tsx, frontend/src/features/Dashboard/components/Pdf/RecentActivity/index.tsx, frontend/src/features/Dashboard/hooks/useExportImages.tsx, frontend/src/features/Dashboard/hooks/useGenerateBrief.ts, frontend/src/features/Dashboard/types.ts
=> [Activité récente] Affichage de toutes les unités dans l'encart global du brief

frontend/src/features/Dashboard/components/Pdf/RecentActivity/RecentActivityByUnit.tsx, frontend/src/features/Dashboard/components/Pdf/RecentActivity/index.tsx
=> [Activité récente] Afficher le nombre de controles sans thématique

frontend/src/features/Dashboard/hooks/useExportImages.tsx, frontend/src/features/map/layers/styles/measurement.style.ts
Et réduction de l'opacité de la zone du tableau de bord
- Resolve #2180
----
=> [Brief] Epaississement de la bordure sur la mini-carte

frontend/src/features/Reportings/useCases/createMissionFromReporting.ts
=> [Signalement] Résolution du bug de création de mission depuis un signalement

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/MissionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/PatchableMissionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/PatchEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/PatchableMissionDataInput.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/PatchMissionEntityUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/PatchMissionUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v2/MissionsITest.kt
=> [Mission] Ajout de propriétés dans l'api publique PATCH des missions 

datascience/src/pipeline/flows/themes_and_tags.py, datascience/src/pipeline/queries/cross/cacem/tags.sql, datascience/src/pipeline/queries/cross/cacem/tags_hashes.sql, datascience/src/pipeline/queries/cross/cacem/themes_hashes.sql, datascience/src/pipeline/queries/monitorenv/tags.sql, datascience/src/pipeline/queries/monitorenv/tags_hashes.sql, datascience/src/pipeline/queries/monitorenv/themes.sql, datascience/src/pipeline/queries/monitorenv/themes_hashes.sql
add row_hash to compare themes and tags on select query + add where condition on select themes and tags
=> [Thématiques et Tag] Ajout d'un row hash au flow pour comparer les themes et les tags

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/Mission/Missions.helpers.ts, frontend/src/features/Mission/components/ControlInfractionsTags.tsx, frontend/src/features/Mission/components/MissionForm/ActionForm/ControlForm/InfractionCard.tsx
=> [Mission] Afficher le bon total des appréhension/saisie dans la timeline de mission

backend/src/main/resources/db/migration/internal/V0.179__migrate_theme_and_tags.sql
Il existe des signalements sans theme.
=> [Thématique] vérifier les themes des signalements pendant la migration.

frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Brief] Amélioration des performances lors de la génération du Brief

datascience/src/pipeline/queries/cross/cacem/themes.sql, datascience/src/pipeline/queries/cross/cacem/themes_hashes.sql, datascience/src/pipeline/queries/monitorenv/themes_hashes.sql, datascience/tests/test_data/cacem_database/V666.504__regulatory_areas_themes_and_tags.sql, datascience/tests/test_pipeline/test_flows/test_regulations.py, datascience/tests/test_pipeline/test_flows/test_themes_and_tags.py
fix: add legacy control_plan_ids to themes flow
=> [Thématiques et tag] Ajout des colonnes legacy au flow

frontend/src/features/Mission/components/MissionForm/ActionForm/index.tsx
=> [Mission] Suppression de l'id du contrôle dans l'entête du formulaire

datascience/src/pipeline/flows/themes_and_tags.py, datascience/tests/test_pipeline/test_flows/test_themes_and_tags.py
=> [Thématiques et tag] Fix le typage

frontend/src/features/Dashboard/components/DashboardsList/Filters.tsx, frontend/src/features/Mission/components/Filters/Map/index.tsx, frontend/src/features/RecentActivity/components/RecentActivityMenuButton/RecentActivityFilters.tsx, frontend/src/features/Reportings/Filters/Map/index.tsx
=> Supprimer tous les préfixes dans les pastilles des filtres côté carto

frontend/package-lock.json, frontend/package.json
Quand on sélectionne un theme ou un tag on ne voyait pas le label en entier.
=> [Thématiques et tag] Correction de l'affichage lors de la selection d'un theme

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt
=> [Mission] Résolution du bug de sauvegarde de mission avec des moyens

backend/src/main/resources/db/migration/internal/V0.184__drop_regulatory_areas_constraints.sql, datascience/src/pipeline/flows/regulations.py
=> [Data] Supprimer les contraintes en base des zones réglementaires

frontend/src/features/RecentActivity/components/Layers/RecentActivityLayerEvents.tsx, frontend/src/features/RecentActivity/components/Overlays/OverlayContent.tsx, frontend/src/features/RecentActivity/components/Overlays/SelectedOverlay.tsx, frontend/src/features/RecentActivity/components/Overlays/index.tsx, frontend/src/features/Reportings/components/ReportingOverlay/Reporting/ReportingCard.tsx, frontend/src/features/layersSelector/search/ResultsList/VigilanceAreaLayer/index.tsx, frontend/src/features/map/index.tsx
=> [Matomo] Ajout d'événements Matomo pour la consultation des signalements et contrôles sur MonitorExt

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/cypress/e2e/side_window/reporting/filters.spec.ts, frontend/cypress/e2e/side_window/vigilance_areas_list/filters.spec.ts, frontend/package-lock.json, frontend/package.json
=> [Thématiques et tag] Sélectionner uniquement les sous-thématiques et les sous-tags

frontend/src/features/Mission/components/MissionForm/hooks/useUpdateMissionZone.ts
Pour éviter des mises à jour intempestives d'une mission, on arrondi les coordonnées de la geom de mission calculée automatiquement depuis un point de contrôle
----
=> [Mission] Arrondir la geom de la mission quand elle est calculée à partir du point de contrôle

frontend/src/components/Tooltip.tsx, frontend/src/features/Dashboard/components/DashboardForm/Footer/CreateMailButton.tsx, frontend/src/features/Dashboard/components/DashboardForm/Footer/index.tsx, frontend/src/features/Dashboard/components/Pdf/Brief.tsx, frontend/src/features/Dashboard/hooks/useExportImages.tsx, frontend/src/features/Dashboard/hooks/useGenerateBrief.ts, frontend/src/features/Dashboard/useCases/exportBrief.ts
=> [Brief] Pouvoir télécharger un brief "abrégé"

.github/workflows/cicd-app.yml
=> [Tech] Mise à jour de la version de Java dans l'action setup-java de la CI

.github/workflows/trivy.yml
=> [Tech] Fix de la version d'ubuntu pour trivy

frontend/src/features/Dashboard/components/Pdf/RecentActivity/RecentActivitySummary.tsx
=> [Brief] Mise à jour de la définition d'une activité récente

frontend/package-lock.json, frontend/src/features/Dashboard/components/Pdf/Attachments/ImagesAttachments.tsx, frontend/src/features/Dashboard/components/Pdf/Attachments/LinksAttachments.tsx, frontend/src/features/Dashboard/components/Pdf/Attachments/index.tsx, frontend/src/features/Dashboard/components/Pdf/Brief.tsx
=> [Brief] Afficher les images en pièce jointe en pleine page et dans la bonne orientation

frontend/package-lock.json, frontend/src/features/LocalizedArea/components/Layers/index.tsx, frontend/src/features/LocalizedArea/constants.ts, frontend/src/features/LocalizedArea/utils.ts
=> [Secteurs localisés] Laisser les secteurs afficher lors du dessin de géométrie et amélioration des couleurs

frontend/cypress/e2e/back_office/station_form.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/CenteredFingerprintLoader.ts, frontend/src/features/Dashboard/components/DashboardForm/components/AmpsPanel.tsx, frontend/src/features/Dashboard/components/DashboardForm/components/RegulatoryAreasPanel.tsx, frontend/src/features/layersSelector/index.tsx, frontend/src/features/layersSelector/metadataPanel/ampMetadata/index.tsx, frontend/src/features/layersSelector/metadataPanel/regulatoryMetadata/index.tsx, frontend/src/pages/Login.tsx, frontend/src/ui/LoadingSpinnerWall.tsx
=> [UI] Utilisation des loaders de monitor-ui

.github/dependabot.yml
Ok pour vous @claire2212 / @maximeperrault  ?
----
=> Tech - Suppression du user `louptheron` des assignés

backend/src/main/resources/db/testdata/V666.15__insert_dummy_vigilance_area.sql, frontend/cypress/e2e/main_window/vigilance_area/delete_vigilance_area.spec.ts, frontend/cypress/e2e/side_window/dashboard/edit_dashboard.spec.ts, frontend/cypress/e2e/side_window/vigilance_areas_list/filters.spec.ts, frontend/src/features/Dashboard/components/DashboardForm/Columns/FirstColumn.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Filters.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/slice.ts, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/useCases/editDashboard.ts, frontend/src/features/VigilanceArea/components/PeriodFilter.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Columns/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Filters/FiltersTag.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Filters/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Filters/slice.ts, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/StatusCell.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Rows/VisibilityCell.tsx, frontend/src/features/VigilanceArea/hooks/useGetFilteredVigilanceAreasQuery.ts, frontend/src/features/VigilanceArea/hooks/useGetVigilanceAreasWithFilters.ts, frontend/src/features/VigilanceArea/useCases/filters/isVigilanceAreaPartOfVisibility.ts, frontend/src/features/layersSelector/search/LayerFilters.tsx, frontend/src/features/layersSelector/search/ResultsList/index.tsx, frontend/src/features/layersSelector/search/SearchInput.tsx, frontend/src/features/layersSelector/search/hooks/useGetFilteredVigilanceAreasForMapQuery.ts, frontend/src/features/layersSelector/search/hooks/useSearchLayers.ts, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/layersSelector/search/slice.ts
Voir ticket pour les règles de gestion
- Resolve #2379 
----
=> [Zone de vigilance] Pouvoir filtrer les zones de vigilance selon leur visibilité (Publique/Interne)

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaReportingRepository.kt
Lié au crash du 07/07/2025
- Resolve #2435
=> [Tech]:Ajout d'une limite dans la récupération des missions et des signalements

frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx
=> [Signalement] Ajout d'un bouton pour copier dans la presse-papier les informations du signalement

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceArea.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/vigilanceArea/CreateOrUpdateVigilanceAreaUTests.kt
=> [Zone de vigilance] Désarchivage des zones de vigilances

frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Panel/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Panel/PanelDates.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Panel/ValidateAt.tsx
=> [Zone de vigilance] Ne pas afficher le bouton de revalidation dans la vue du Tableau de bord

frontend/src/api/infractionsAPI.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Target/HistoryOfInfractions.tsx, frontend/src/features/Reportings/components/ReportingForm/hooks/useGetHistoryOfInfractions.ts
=> [Signalement] Ajouter les antécédents lors de la copie d'informations dans le presse-papier

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaDashboardRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaDashboardRepositoryITests.kt
=> [Tableau de bord] Supprimer les données enregistrées d'un tableau de bord lors de sa suppression

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/dashboard/EditableBriefVigilanceAreaEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/file/dashboard/AttachmentFile.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/file/dashboard/BriefFileWriter.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/file/dashboard/DashboardFile.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/utils/Base64Converter.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/utils/ByteArrayConverter.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/utils/OfficeConverter.kt, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/Dashboard/components/DashboardForm/Footer/index.tsx, frontend/src/features/Dashboard/hooks/useGenerateEditableBrief.ts, frontend/src/features/Dashboard/types.ts, frontend/src/features/Dashboard/useCases/exportBrief.ts, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Footer.tsx, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Target/HistoryOfInfractions.tsx, frontend/src/features/Reportings/components/ReportingForm/hooks/useGetHistoryOfInfractions.ts
=> [Brief] Ajout des images des Zones de vigilance dans le document éditable

frontend/src/features/VigilanceArea/types.ts, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.test.ts, frontend/src/features/layersSelector/utils/getFilteredVigilanceAreasPerPeriod.ts
=> [Zone de vigilance] Ajout des filtres sur les 3 et 12 dernieres mois

frontend/cypress/e2e/main_window/reporting/create_reporting.spec.ts, frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/api/googlePlacesAPI/googlePlacesAPI.ts, frontend/src/domain/entities/layers/constants.ts, frontend/src/domain/shared_slices/Map.ts, frontend/src/features/LocateOnMap/Layer.tsx, frontend/src/features/LocateOnMap/hook/useBeaches.ts, frontend/src/features/LocateOnMap/index.tsx, frontend/src/features/map/index.tsx
- Mise à jour de l'api google
- Affichage d'un encadré rouge de la zone sélectionnée
- Affichage du résultat dans le champ de recherche -> la suppression de la recherche enlève l'encadré rouge
A voir avec le CACEM ultérieurement : les plages renseignées dans QGIS ne permettent pas de faire cet encadré.
- Resolve #2248 
----
=> [Recherche] Affichage d'un encadré rouge suite à une recherche de lieu

frontend/cypress/e2e/main_window/monitor-ext.spec.ts, frontend/src/components/Menu.tsx, frontend/src/features/InterestPoint/components/EditInterestPoint.tsx, frontend/src/features/map/index.tsx
=> [MonitorExt] Ajout de la fonctionnalité des points d'intérêts 

frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Brief] Passage des images des zones en HD

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBEnvActionRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt
=> [Mission] Suppression des actions quand on supprime la mission
