frontend/src/features/map/layers/missionGeometryHelpers.ts
Il fallait afficher le nombre de contrôle par actions de contrôle sur la pop-up de mission
- Resolve #140
=> [MissionPopUp] Fix number of controls bug in mission pop-up

frontend/src/features/map/MapExtentController.ts
Dans le cas où la géométrie n'est pas valide. Pourrait éventuellement arriver car pas de validation des géométries coté back.
=> [carte] : fix bug lorsqu'on zoom sur une étendue non valide

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsController.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsControllerITests.kt
=> [DO NOT MERGE] [Missions] Ajout du paramètre source de missions sur l'api des missions publique

frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MultiPointPicker.tsx, frontend/src/features/missions/MultiZonePicker.tsx
- Resolve #571 
- Resolve #570
=> [Surveillance] Lors de l'édition de la zone de surveillance le bouton "zone identique a zone de mission" est décoché et inactif

frontend/public/semaphore.svg, frontend/src/features/Semaphores/SearchSemaphoreButton/SearchSemaphores.tsx, frontend/src/features/map/layers/Semaphores/semaphores.style.ts, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx, frontend/src/features/map/overlays/position.js, frontend/src/features/map/overlays/semaphores/SemaphoreCard.tsx, frontend/src/features/map/overlays/semaphores/index.tsx, frontend/src/pages/HomePage.tsx
- Resolve #465 
lien des retours d'Adeline traités dans cette PR : https://github.com/MTES-MCT/monitorenv/issues/465#issuecomment-1578808624
A noter : 
- vu avec Adeline, lors du zoom sur la carte on enlève le trait reliant la pop-up du sémaphore et le sémaphore de la carte pour éviter un rendu étrange (la ligne ne se met pas à jour)
=> [Semaphores] Améliorations design

frontend/src/features/coordinates/DDCoordinatesInput.tsx, frontend/src/features/coordinates/DMDCoordinatesInput.tsx, frontend/src/features/coordinates/DMSCoordinatesInput.tsx, frontend/src/features/map/tools/interest_points/EditInterestPoint.tsx, frontend/src/features/missions/MissionForm/ActionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ActionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/ControlForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionCard.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm.tsx, frontend/src/features/missions/MissionForm/ActionsForm.tsx, frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx, frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/Schemas/index.ts, frontend/src/features/missions/MissionForm/index.tsx, frontend/src/features/missions/MultiPointPicker.tsx, frontend/src/features/missions/MultiZonePicker.tsx
- Resolve #528 (On garde la possibilité d'éditer la zone de mission et d'ajouter des actions même si la mission est clôturée)
- Résolution du bug qui masquait la poubelle au niveau des unités (en cas de multiples unités)
- Affichage du format des coordonnées en plus foncé (fenêtre d'édition d'un point de contrôle)
=> [Mission] Accès à l'édition complète de la mission même si elle est clôturée, résolution du bug de suppression des unités multiples

frontend/src/features/missions/MissionForm/MissionForm.tsx
=> [Mission] Garder coché la case "dates et heures de surveillance équivalentes à celles de la mission" quand on revient sur une mission

frontend/src/domain/entities/map/constants.ts, frontend/src/domain/shared_slices/Map.ts, frontend/src/domain/shared_slices/Measurement.ts, frontend/src/domain/use_cases/map/updateMeasurementsWithNewDistanceUnit.ts, frontend/src/domain/use_cases/measurement/saveMeasurement.ts, frontend/src/features/map/BaseMap.tsx, frontend/src/features/map/controls/MapCoordinatesBox.tsx, frontend/src/features/map/layers/MeasurementLayer.tsx, frontend/src/features/map/overlays/MeasurementOverlay.tsx, frontend/src/features/map/tools/measurements/CustomCircleRange.tsx, frontend/src/store.ts
- Resolve #34 
Ajout d'un sélecteur pour changer les unités de distance
Répercussion sur l'outil de tracé d'un point ou d'une ligne (même comportement que pour les unité de coordonnées)
=> [Map] Ajout de la possibilité de changer l'unité de distance (mètres/kms ou nautiques)

frontend/src/uiMonitor/ol-override.css
- Depuis la mise en place du sélecteur d'unités de distance il y avait un doublon d'affichage des boutons de zoom (ils était cachés derrière le bouton de sélection de zones)
=> [Map] Ne pas afficher les boutons de zoom qui sont en doublons sur la carte

frontend/cypress/e2e/side_window/mission/create_mission.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/api/missionsAPI.ts, frontend/src/features/missions/MissionForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm.tsx
- Resolve https://github.com/MTES-MCT/monitorfish/issues/2480
=> [Missions] Affichage d'une unité déjà mobilisé 

backend/src/main/resources/db/testdata/V666.5__insert_dummy_missions.sql, frontend/cypress/e2e/side_window/mission/close_mission_validation.spec.ts, frontend/cypress/e2e/side_window/mission/create_mission.spec.ts, frontend/cypress/e2e/side_window/mission/mission_actions.spec.ts, frontend/cypress/e2e/side_window/mission/mission_dates_validation.spec.ts, frontend/src/features/map/tools/measurements/CustomCircleRange.tsx, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/formikUseCases/updateActionThemes.ts, frontend/src/features/missions/MissionForm/index.tsx, frontend/src/features/missions/Missions.helpers.ts
- Resolve #34
- Remet à jour le champ `isClosed` à `true` dans une mission si l'utilisateur essaye de la réouvrir alors que le formulaire à des erreurs
=> [OutilDeMesure] Bouton de validation pour tracé un cercle inactif si les deux champs ne sont pas remplis

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/cypress/e2e/side_window/mission_list/missions.spec.ts, frontend/cypress/e2e/side_window/reporting/filters.spec.ts, frontend/cypress/e2e/side_window/reporting/reportings.spec.ts, frontend/package.json, frontend/src/api/missionsAPI.ts, frontend/src/api/reportingsAPI.ts, frontend/src/domain/entities/missions.ts, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/domain/shared_slices/ReportingsFilters.ts, frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedAdministrationNames.ts, frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedControlUnitIds.ts, frontend/src/domain/use_cases/missions/filters/isMissionPartOfSelectedThemes.ts, frontend/src/domain/use_cases/reporting/filters/sourceFilterFunction.ts, frontend/src/domain/use_cases/reporting/filters/subThemesFilterFunction.ts, frontend/src/domain/use_cases/reporting/filters/themeFilterFunction.ts, frontend/src/features/Reportings/Filters/Map/index.tsx, frontend/src/features/Reportings/Filters/Table/FilterTags.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/index.tsx, frontend/src/features/Reportings/Filters/style.ts, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts, frontend/src/features/layersSelector/search/LayerFilters.tsx, frontend/src/features/layersSelector/search/index.tsx, frontend/src/features/missions/MissionsList/Filters/FilterTags.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx, frontend/src/hooks/useGetFilteredMissionsQuery.ts
- Resolve #372 
- Resolve #921
----
=> [Mission] Amélioration de la recherche des unités et résolution du bug à la sélection du type de cible

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/AdministrationModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitContactModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/ControlUnitResourceModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/DepartmentAreaModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionControlResourceModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/MissionModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/StationModel.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepositoryITests.kt
=> [Missions] Impossible de modifier les unités ou moyens des anciennes missions lorsqu'il y a au moins un moyen rattaché

backend/src/main/resources/db/migration/internal/V0.102__fix_mission_control_resources_id_sequence.sql
=> [Missions] Impossible de modifier les unités ou moyens des anciennes missions lorsqu'il y a au moins un moyen rattaché (bis)

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMissions.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetMissionsUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsControllerITests.kt
Réparation des tests autour des modifications sur GetMissions
Je me suis aussi rendu compte que les tests pour GetMissions n'étaient pas run. Ils le sont désormais.
----
=> [Missions] Tests pour filtrer les missions par unité de contrôle

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionWithActionsAndAttachedReporting.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionWithAttachedReporting.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/CreateOrUpdateMissionDataInput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/v1/Missions.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActionsUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionWithActionsAndAttachedReportingUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionWithAttachedReportingUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/bff/MissionsITests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/ApiMissionsITests.kt
resolves #879 
Voir si les tests sont suffisants.
Peut être un changement coté Fish à faire pour éviter d'envoyer les envActions ?
=> [Missions] API publique ne peut pas écrire sur les envActions

frontend/.eslintrc.js
- Lorsque c'est un test booléen : ne pas remplacer `||` par `??` mais conserver le `||` tout en s'assurant que toutes le valeurs de la condition sont bien castées en booléens (`!!`).
- Lorsqu'il s'agit d'une valeur par défaut  : remplacer `||` par `??`.
La première condition n'est pas couverte par le lint, c'est à nous d'y prêter attention ^^.
None
----
=> [Tech] Add lint warning for nullish coalescing operator enforcement

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/features/map/overlays/missions/MissionCard.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitSelector.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/ControlUnitWarningMessage.tsx, frontend/src/features/missions/MissionForm/ControlUnitsForm/index.tsx
Règle de gestion: 
- Pour la première unité, si elle est déjà en cours de mission on affiche le warning et on rend disabled le bouton permettant d'ajouter une autre unité
- Si l'utilisateur conserve la mission, le bouton d'ajout d'unité est à nouveau accessible et on répète le comportement précédent
- Resolve #1119
----
=> [Mission] Gestion du "multi-unité" dans une mission pour l'affichage du warning d'unité déjà en cours de mission

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionUTests.kt
=> [Missions] Correction du champ `createdAtUtc` retourné lors d'un `update`

frontend/src/App.tsx, frontend/src/index.tsx, frontend/tsconfig.json
- J'aurais pu mettre un `"@/*": ["*"],` mais je préfère être déclaratif pour ne garder que les paths qui correspondent à notre structure "officielle".
- La raison pour laquelle je n'ai pas mis les dossiers `context/`, `errors/` et `workers/` et que j'aimerais challenger leur emplacement actuel.
- MTES-MCT/monitorfish#2886
----
=> [Tech] Configure les paths dans tsconfig

frontend/cypress/e2e/side_window/mission_form/main_form.spec.ts, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/features/map/layers/Reportings/style.ts, frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts, frontend/src/features/missions/MissionForm/slice.ts
J'ai créée une nouvelle action spécifique pour la création de mission. Elle vient supprimer la mission dans le store avec l'id `new-xxx` et restocker la mission à jour (avec le bon id) dans le store.
J'ai également diminuer le délai du callback ici :  useSyncFormValuesWithRedux.ts, qui, je pense, était trop long et posait des soucis de mise à jour de données (notamment avec le nouvel id)
- Resolve #1292
----
=> [Mission] Résolution du bug de duplication de mission à la création

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/map/BaseMap.tsx, frontend/src/features/map/ZoomListener.tsx, frontend/src/features/map/index.tsx, frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
J'ai supprimé les dépendances dans le usecallback appelé lors du zoom sur la carte. Cela faisait laguer le zoom et l'appli était comme "bloquée"
Bug introduit dans cette PR : https://github.com/MTES-MCT/monitorenv/pull/1260
----
=> [Carte] Résolution du bug au zoom sur la carte

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IPostgisFunctionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/reportings/CreateOrUpdateReporting.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaPostgisFunctionRepository.kt, backend/src/main/resources/db/migration/internal/V0.116__fix_geometries.sql, backend/src/main/resources/db/migration/internal/V0.121__fix_geometries.sql, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/CreateOrUpdateReportingUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateEnvActionsUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/CreateOrUpdateMissionUTests.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaPostgisFunctionRepositoryITests.kt
relates to #461 
A compléter avec un fix front
On normalise les géométries uniquement lorsqu'elles sont tracées au delà de 230° et non 180° car on veut pouvoir quand même visualiser correctement les zones tracées à proximité de la ligne de franchissement des 180° (Wallis et Futuna / Papette)
A vérifier que l'on a bien les façades à ces coordonnées.
=> [Geometries] Normalisation des géométries pour les missions, envActions et signalements

frontend/src/features/map/draw/DrawModal.tsx
Ajout des boutons des types de zone dans la modal pour dessiner la zone de surveillance
- Resolve #1313
----
=> [Surveillance] Ajout des boutons de "type" de zone pour dessiner la zone de surveillance

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/repositories/IMissionRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/GetFullMissions.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaMissionRepository.kt
En supprimant le filtre `missionSources` on récupérait les missions historiques de Poseidon
=> [Mission] Résolution du bug de l'api /missions qui renvoyait les missions Poseidon

frontend/src/features/missions/MissionForm/utils.ts
J'avais ajouté les `attachedReportingIds`, `detachedReportingIds` dans le `omit` qui comparait le `nextValues` et `previousValues` pour savoir s'il fallait faire un `saveMission`. On ne sauvegardait donc plus la mission au rattachmeent ou détachement d'un reporting
=> [Mission] Fix du bug au rattachement d'un signalement

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/use_cases/missions/saveMission.ts, frontend/src/features/missions/MissionForm/Schemas/Control.ts, frontend/src/features/missions/MissionForm/Schemas/Surveillance.ts
=> [Mission] Le trigramme "complété par" des actions n'est plus obligatoire

frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx, frontend/src/features/Station/components/StationLayer/utils.ts
- La hauteur de la modal s'adapte maintenant au contenu
- Resolve #1105
----
=> [Unité de contrôle] La modal d'édition d'une unité s'adapte en hauteur au contenu

frontend/src/features/layersSelector/myAmps/MyAMPLayerGroup.tsx, frontend/src/features/layersSelector/search/LayerFilters.tsx, frontend/src/features/layersSelector/search/SearchInput.tsx, frontend/src/features/layersSelector/utils/LayerSelector.style.ts
- Resolve #1004
- Resolve #1130
----
=> [Thématiques] Ajouter une possibilité de recherche dans le menu des filtres "thématique réglementaire"

frontend/cypress/e2e/side_window/mission_form/attach_actions_to_reportings_in_mission.spec.ts, frontend/cypress/e2e/utils/createReportingOnSideWindow.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionForm/InfractionForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx, frontend/src/features/missions/MissionForm/Schemas/Control.ts, frontend/src/features/missions/MissionForm/Schemas/Infraction.ts
Modifier les informations d'un contrôle (thématiques, sous-thématiques, et données de la cible de l'infraction) lorsque l'utilisateur avait rattaché le contrôle à un signalement et qu'il change le signalement rattaché au contrôle.
- Resolve #1381
----
=> [Contrôle] Mettre à jour les informations d'un contrôle lorsqu'on change le signalement rattaché à cette action

frontend/src/features/Administration/components/AdministrationForm/constants.tsx, frontend/src/features/ControlUnit/components/ControlUnitForm/constants.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Validity.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/index.tsx, frontend/src/features/missions/MissionForm/GeneralInformationsForm.tsx, frontend/src/features/missions/MissionsList/Filters/index.tsx
- Fix des datePicker sans `baseContainer`
- Taille fixe de 400px pour les colonnes `nom` des tableaux du back office
- Resolve #1460
=> [BackOffice] Résolution du souci d'affichage des tableaux dans le backoffice

frontend/cypress/e2e/side_window/mission_list/filters.spec.ts, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts, frontend/src/hooks/useGetFilteredMissionsQuery.ts
Suite à une mise à jour de la façon de gérer le filtre de date j'avais copié/collé le filtre des reportings qui va chercher les dernières 24H au lieu du jour en cours pour les missions
- Resolve #1466
----
=> [Mission] Résolution du bug sur le filtre de date "aujourd'hui" dans la liste des missions

frontend/src/domain/shared_slices/LayerSidebar.ts, frontend/src/features/Reportings/components/ReportingLayer/Reporting/SelectedReporting.tsx, frontend/src/features/Reportings/components/ReportingOverlay/Reporting/ReportingCard.tsx, frontend/src/features/Reportings/hooks/useGetFilteredReportingsQuery.ts, frontend/src/features/Semaphore/components/Layer/SelectedSemaphoreLayer.tsx, frontend/src/features/Semaphore/components/Layer/index.ts, frontend/src/features/Semaphore/components/Layer/utils.ts, frontend/src/features/layersSelector/search/ResultsList/index.tsx, frontend/src/features/layersSelector/search/slice.ts
- Je n'affiche le lien entre le sémaphore et les signalements que pour les sémaphores visibles (suivant les filtres appliqués)
- Je ferme les menu sdu sélecteur de layer quand j'ouvre le menu des résultats de recherches des AMPS ou des zones règlementaires (voir commentaire d'Adeline en bas du ticket 1445)
- Resolve #1445
- Resolve #1399 
----
=> [Carte] Résolution du bug sur le lien Sémaphore/ Signalements

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/domain/use_cases/missions/switchTab.ts, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/InfractionsForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ControlForm/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/NoteForm.tsx, frontend/src/features/missions/MissionForm/ActionForm/ReportingForm/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/SurveillanceForm/index.tsx, frontend/src/features/missions/MissionForm/ActionForm/index.tsx, frontend/src/features/missions/MissionForm/ActionsTimeLine/index.tsx, frontend/src/features/missions/MissionForm/MissionForm.tsx, frontend/src/features/missions/MissionForm/hooks/useSyncFormValuesWithRedux.ts, frontend/src/features/missions/MissionForm/index.tsx, frontend/src/features/missions/MissionForm/slice.ts
=> [MISSION] Garder le formulaire des infractions ouverts

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/MissionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/entities/mission/PatchableMissionEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/PatchEntity.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/actions/PatchEnvAction.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/PatchMission.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/publicapi/inputs/PatchableMissionDataInput.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/PatchEnvActionEntityUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/mappers/PatchMissionEntityUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/actions/PatchEnvActionUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/PatchMissionUTest.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/domain/use_cases/missions/fixtures/MissionFixture.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/endpoints/publicapi/v2/MissionsITest.kt
Similairement au champ 'observationsByUnit', j'aimerais rendre les champs start/endDateTime patchable. 
Il est beaucoup plus facile pour nous d'utiliser l'endpoint v2 pour patcher plutot que l'endpoint v1 qui requiert toute la mission
----
=> [Tech] set Mission's start/endDateTime as patchable

frontend/src/features/Reportings/Filters/ReportingSearch.tsx, frontend/src/features/missions/MissionsSearch.tsx
=> [Mission & Signalement] : suppression de la limite de la recherche

frontend/src/features/layersSelector/search/ResultsList/VigilanceAreaLayer/index.tsx
Suppression du doublon du nom de la zone de vigilance dans la liste des résultats de recherche
- Resolve #1578 
----
=> [Zone de vigilance] Résolution du bug de doublon de nom de la zone dans la liste des résultats

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/missions/MissionForm/Schemas/Infraction.ts, frontend/src/features/missions/Missions.helpers.ts
=> [Action & Infraction] Créer un nouvel id pour chaque élément dupliqué

frontend/src/features/map/overlays/OverlayPositionOnCentroid.tsx
=> [Tech] Ne plus afficher les zones de mission quand on ouvre une autre pop-up

frontend/src/components/NavBar.tsx, frontend/src/domain/entities/sideWindow.ts, frontend/src/features/Dashboard/components/DashboardForm/index.tsx, frontend/src/features/Dashboard/components/DashboardMapButton.tsx, frontend/src/features/Dashboard/components/DashboardsList/index.tsx, frontend/src/features/Dashboard/components/DashboardsNavBar.tsx, frontend/src/features/Reportings/components/ReportingsList/index.tsx, frontend/src/features/SideWindow/index.tsx, frontend/src/features/SideWindow/style.ts, frontend/src/features/missions/MissionsList/index.tsx, frontend/src/features/missions/MissionsNavBar.tsx, frontend/src/utils/routes.ts
=> [Tableau de bord et brief] Création de la page Dashboard et ajout des onglets de navigation

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/api/adapters/bff/outputs/ExtractedAreaDataOutput.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/model/VigilanceAreaModel.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/interfaces/IDBVigilanceAreaRepository.kt, backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaVigilanceAreaRepositoryITests.kt, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/ImageViewer.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/PhotoUploader.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/VigilanceAreaPanel.tsx, frontend/src/features/layersSelector/index.tsx
- Résolution du souci de z-index
- Prise en compte des retours d'Adeline (voir ticket)
- Amélioration des perfs grâce à l'EntiyGraph + on ne renvoie plus les images dans l'api qui récupère les zones de vigilances depuis une zone dessinée
- Resolve #1643
----
=> [Zone de vigilance] Amélioration UI/UX de la fonctionnalité d'ajout d'images

frontend/cypress/e2e/side_window/mission_form/mission_zone.spec.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/CustomGlobalStyle.ts, frontend/src/domain/shared_slices/Global.ts, frontend/src/features/Dashboard/Layers/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/ListLayerGroup.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/Panel.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/SelectedAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/SmallAccordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/index.tsx, frontend/src/features/Dashboard/components/DashboardsList/index.tsx, frontend/src/features/Dashboard/components/DashboardsNavBar.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/types.ts, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddAMPs/AMPItem.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/AddRegulatoryAreas/RegulatoryAreaItem.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/ImageViewer.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreaForm/index.tsx, frontend/src/features/layersSelector/index.tsx, frontend/src/features/layersSelector/metadataPanel/MetadataPanel.style.ts, frontend/src/features/layersSelector/overlays/OverlayContent.tsx, frontend/src/features/layersSelector/utils/LayerLegend.style.tsx, frontend/src/features/layersSelector/utils/LayerSelector.style.ts, frontend/src/features/map/index.tsx
- Création du composant `Accordion`
- Gestion de la fermeture des autres accordéons 
- Pour le moment j'ai mis un click sur toute la longueur du titre s'il n'y a pas d'autre bouton dans le titre, s'il y en a il faut cliquer sur le chevron pour ouvrir/ fermer l'accordéon
- Ajout du bloc "Zones réglementaires"
- Resolve #1714
=> [Dashboard] Bloc zones réglementaires + Création du composant accordéon

frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/useCases/editDashboard.ts, frontend/src/features/Dashboard/useCases/editDashboardArea.ts, frontend/src/features/Dashboard/utils.ts
=> [Tableau de bord]: ne pas filtrer les objets épinglés par rapport à la zone

frontend/src/features/ControlUnit/utils.ts, frontend/src/features/Dashboard/components/DashboardForm/Comments/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/DashboardForm.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/Filters.tsx, frontend/src/features/Dashboard/components/DashboardForm/Toolbar/Filters/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/slice.ts, frontend/src/features/Dashboard/slice.ts, frontend/src/features/Dashboard/useCases/createDashboard.ts, frontend/src/features/Dashboard/useCases/deleteDashboard.ts, frontend/src/features/Dashboard/useCases/editDashboard.ts, frontend/src/features/Dashboard/useCases/filterReportings.test.ts, frontend/src/features/Dashboard/useCases/filterReportings.ts, frontend/src/store/reducers.ts
=> [Tableau de bord et Brief] Corrections de bugs

frontend/src/features/ControlUnit/components/ControlUnitDialog/ControlUnitResourceList/Item.tsx, frontend/src/features/ControlUnit/components/ControlUnitDialog/index.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/FilterBar.tsx, frontend/src/features/ControlUnit/components/ControlUnitListDialog/index.tsx, frontend/src/features/ControlUnit/useCases/getFilteredControlUnits.ts, frontend/src/features/ControlUnit/utils.ts, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Station/components/StationLayer/index.ts, frontend/src/features/map/MapExtentController.ts
- Amélioration de la racherche par administartion, type et base (côté carte et dans les tableaux de bord)
- Ajout d'un bouton de retour depuis la fiche Unité pour retourner sur la vue liste
- Filtrer les bases sur la carte suivant les filtres appliqués dans la recherche d'unités de contrôle
- Ajout d'un zoom vers la base au niveau de chaque moyen (dans la fiche Unité)
- Ajout de la recherche par nom de moyen dans le champ de recherche
- Resolve #1048 
- Resolve #1758 
- Resolve #1675 
----
=> [Unités de contrôle] Amélioration de la recherche, zoom sur les moyens, retour en arrière depuis la fiche unité

frontend/package-lock.json, frontend/package.json, frontend/src/features/Dashboard/components/DashboardsList/Columns/index.tsx, frontend/src/features/Dashboard/components/DashboardsList/DashboardsTable.tsx, frontend/src/features/Dashboard/components/DashboardsList/index.tsx, frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/components/Layers/PreviewDashboardLayer.tsx, frontend/src/features/Reportings/components/ReportingsList/Columns/index.tsx, frontend/src/features/Reportings/components/ReportingsList/ReportingsTable.tsx, frontend/src/features/Reportings/components/ReportingsList/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/Columns/index.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/VigilanceAreasTable.tsx, frontend/src/features/VigilanceArea/components/VigilanceAreasList/index.tsx, frontend/src/features/missions/MissionsList/Columns/index.tsx, frontend/src/features/missions/MissionsList/MissionsTable.tsx, frontend/src/features/missions/MissionsList/index.tsx, frontend/src/hooks/useTable.ts
-  `isLoading` est a `true` au premier appel api => on affiche un tableau avec le Skeleton
- `isFetching` est a `true` lors du refetch des datas => on change les cellules pour éviter de re-render le tableau complètement et qu'il scroll tout en haut
- Resolve #1454
----
=> [Listes] Correction du bug qui remontaient les listes lors du rafraîchissement des données

.github/workflows/cicd-app.yml, frontend/src/features/map/BaseMap.tsx, frontend/src/index.tsx
Activation du strict mode + ajout de timeouts sur les jobs + annulation des workflows déjà en cours au push
- Resolve #1654
----
=> [Tech] Active le mode strict pour React 

frontend/config/cypress.config.ts, frontend/package-lock.json, frontend/package.json, frontend/src/domain/shared_slices/MissionFilters.ts, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/slice.ts, frontend/src/features/Reportings/Filters/Map/index.tsx, frontend/src/features/Reportings/Filters/Table/index.tsx, frontend/src/features/Reportings/Filters/index.tsx, frontend/src/features/Semaphore/components/Overlay/SemaphoreCard.tsx, frontend/src/features/Semaphore/components/SearchSemaphoreButton/SearchSemaphores.tsx, frontend/src/features/coordinates/DDCoordinatesInput.tsx, frontend/src/features/coordinates/SetCoordinates.tsx, frontend/src/features/map/layers/MeasurementLayer.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/TagsSelector.tsx, frontend/src/features/missions/MissionForm/ActionForm/Themes/ThemeSelector/SubThemesSelector.tsx, frontend/src/features/missions/components/Filters/Map/index.tsx, frontend/src/features/missions/components/Filters/Table/index.tsx, frontend/src/features/missions/components/Filters/index.tsx, frontend/src/utils/geometryValidation.ts, frontend/src/utils/getRegulatoryThemesAsOptions.ts
- Modification suite au retour de Manon : https://github.com/MTES-MCT/monitorenv/issues/1832#issuecomment-2483051558
- Remplacement suppression des `as any`
- Resolve #1832
----
=> [Signalements] Afficher la liste des signalements depuis un sémaphore avec un filtre de un mois

frontend/src/domain/entities/layers/index.ts, frontend/src/domain/shared_slices/Draw.ts, frontend/src/domain/use_cases/draw/eraseDrawedGeometries.ts, frontend/src/features/Dashboard/components/DashboardForm/Toolbar/EditArea/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Toolbar/index.tsx, frontend/src/features/Dashboard/components/Layers/ActiveDashboardLayer.tsx, frontend/src/features/Dashboard/slice.ts, frontend/src/features/commonComponents/Modals/MapInteraction.tsx, frontend/src/features/map/draw/DrawModal.tsx, frontend/src/features/map/layers/DrawLayer.ts, frontend/src/hooks/useDrawVectorLayer.ts, frontend/src/utils/geometryValidation.ts
=> [Tableau de bord] Ajout d'un bouton pour effacer la zone lors de l'édition

frontend/src/api/api.ts, frontend/src/features/Reportings/components/ReportingForm/AttachMission/AttachMissionToReportingModal.tsx, frontend/src/features/Reportings/components/ReportingForm/FormComponents/Validity.tsx, frontend/src/features/Reportings/components/ReportingForm/FormContent.tsx, frontend/src/features/commonComponents/Modals/MapInteraction.tsx, frontend/src/features/missions/MissionForm/ActionsTimeLine/ActionCard/EnvActions/index.tsx, frontend/src/features/missions/MissionForm/ActionsTimeLine/ActionCard/style.ts, frontend/src/features/missions/MissionForm/AttachReporting/AttachReportingToMissionModal.tsx, frontend/src/store/index.ts, frontend/src/store/reducers.ts
- Ajout de la fonction `onCancel` sur la pop-up de rattachement d'une mission à un signalement et la pop-up de rattachement d'un signalement à une mission.
- Lorsqu'on veut ré-ouvrir un signalement archivé, ajout d'un scroll vers le champ "Validité" pour signaler un souci au niveau des dates : 
- Mettre l'encart des signalements dans la timeline des missions en bleu si de type Observation
- Resolve #1767
- Resolve #1846 
----
=> [Reporting] Pouvoir fermer la pop-up de rattachement d'une signalement à une mission

frontend/src/features/Mission/components/MissionForm/slice.ts, frontend/src/features/Mission/components/MissionForm/sse.ts, frontend/src/features/Reportings/components/ReportingForm/sse.ts
=> [Mission] Passer les valeurs reçues de `missionEvent` à `undefined` au lieu de `null`

frontend/src/domain/use_cases/administrative/showAdministrativeLayer.ts, frontend/src/features/map/layers/styles/administrativeAndRegulatoryLayers.style.ts
Au zoom sur les départements qui comprennent plusieurs îles (Guadeloupe par exemple) le nom du département s'affichait au niveau de chaque île. J'ai mis le texte sur le centre de la géométrie
- Resolve #1941
----
=> [Zones Administratives] N'afficher qu'une seule fois le nom des départements

frontend/src/features/Dashboard/components/Pdf/v1/Comments/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/Comments/index.tsx
=> [Brief] Modification de la séparation du bloc commentaire

frontend/src/features/Mission/components/Layers/index.tsx, frontend/src/features/Reportings/components/ReportingLayer/Reporting/index.tsx
=> [Signalements] Laisser les signalements affichés sur la carte lors du dessin d'un point ou d'une zone d'un signalement

frontend/cypress/e2e/side_window/dashboard/edit_dashboard.spec.ts, frontend/src/features/Dashboard/components/DashboardForm/Accordion.tsx, frontend/src/features/Dashboard/components/DashboardForm/Amps/ListLayerGroup.tsx, frontend/src/features/Dashboard/components/DashboardForm/Amps/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Comments/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/SelectedControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ControlUnits/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/ListLayerGroup.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/Reportings/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/TerritorialPressure/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ToggleSelectAll/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/ToggleSelectAll/style.ts, frontend/src/features/Dashboard/components/DashboardForm/ToggleSelectAll/utils.tsx, frontend/src/features/Dashboard/components/DashboardForm/Toolbar/Filters/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/DashboardForm/style.ts, frontend/src/features/Dashboard/components/DashboardsList/index.tsx, frontend/src/features/Dashboard/components/MenuButton.tsx, frontend/src/features/Dashboard/utils.ts, frontend/src/features/Dashboard/utils.tsx
=> [Tableau de bord] Épingler en groupe

backend/src/main/resources/db/migration/internal/V0.169__update_reporting_actions_view.sql, backend/src/main/resources/db/migration/internal/V0.170__exclude_actions_without_unit_from_analytic_actions.sql
Demande Morgan concernant la vue `reporting_actions`.
Pour la vue `analytics_actions`, j'exclus les actions sans unité associée (15 contrôles de Poséidon en 2021/2022).
=> Mise à jour de la vue `reporting_actions` et `analytics_actions`

frontend/src/features/Dashboard/components/DashboardForm/slice.ts, frontend/src/features/Dashboard/components/Pdf/v1/Brief.tsx, frontend/src/features/Dashboard/components/Pdf/v1/GeneratePdfButton.tsx, frontend/src/features/Dashboard/components/Pdf/v1/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v1/style.ts, frontend/src/features/Dashboard/components/Pdf/v2/Table/index.tsx, frontend/src/features/Dashboard/components/Pdf/v2/style.ts, frontend/src/features/Dashboard/hooks/useExportImages.tsx
=> [Brief] Ajout de la vue globale des zones sélectionnées

.github/workflows/cicd-database.yml
Car 1/ pas nécessaire et 2/ cause de bugs car la CI tourne à chaque release
=> Désactiver les builds automatiques d'images de base de données

frontend/src/features/Dashboard/components/DashboardsList/Filters.tsx, frontend/src/features/Dashboard/components/DashboardsList/Rows/RegulatoryAreasThemesCell.tsx, frontend/src/features/Dashboard/useCases/filters/filterByRegulatoryThemes.ts, frontend/src/features/Mission/components/Filters/Map/index.tsx
Il y avait un souci parce que les thématiques dans les zones reg sont des tableaux de string.
J'ai également supprimé les mot `thème` des tags de filtres côté carto (ticket 2093)
- Resolve #1928 
- Resolve #2093 
----
=> [Tableau de bord & brief] Résolution du bug sur le filtre par thématique dans la vue liste

frontend/cypress/e2e/side_window/mission_form/mission_actions.spec.ts, frontend/src/features/Mission/components/MissionForm/ActionForm/ControlForm/index.tsx
=> [Mission] Vider le champ Type de véhicule lors de la mise à jour du champ Type de cible

frontend/src/features/VigilanceArea/components/VigilanceAreaForm/Panel/PanelPeriodAndThemes.tsx, frontend/src/features/layersSelector/metadataPanel/regulatoryMetadata/Identification.tsx
Uniquement si elles sont absentes.
=> [Thématiques et tag] Cacher les sous-thématiques et sous-tags dans les résumés des zones de vigilances et des zones réglementaires

backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitContactRepository.kt, backend/src/main/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitResourceRepository.kt
La liste des unités de contrôle ne se mettait pas à jour lors de l'ajout/modification de moyen ou de contact
----
=> [Unité de contrôle] Résolution du bug de cache sur l'ajout de moyen et de contact à une unité de contrôle

frontend/cypress/e2e/side_window/dashboard/edit_dashboard.spec.ts, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Layer.tsx
=> [Tableau de bord] Mise à jour du tag des zones de vigilance pour afficher "INTERNE" à la place de "CACEM"

backend/src/test/kotlin/fr/gouv/cacem/monitorenv/infrastructure/database/repositories/JpaControlUnitRepositoryITests.kt, frontend/src/context/mission/MissionEventContext.tsx, frontend/src/features/Mission/components/MissionForm/FormikSyncMissionFields.tsx, frontend/src/features/Mission/components/MissionForm/constants.ts, frontend/src/features/Mission/components/MissionForm/hooks/useListenMissionEventUpdates.ts, frontend/src/features/Mission/components/MissionForm/sse.ts
L'event `MISSION_UPDATE` écoutait aussi les changements du champ `attachedReportings` donc comme on reçoit une `MissionEntity` la propriété était vide à chaque, supprimant ainsi les signalements.
Maintenant je vérifie les changements dans les champs suivant le type de l'événement
----
=> [Mission] Résolution du bug avec les événements de mise à jour automatique d'une mission

frontend/src/features/Dashboard/components/DashboardForm/Amps/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/RegulatoryAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/VigilanceAreas/Layer.tsx, frontend/src/features/Dashboard/components/DashboardForm/style.ts, frontend/src/features/Dashboard/components/Pdf/VigilanceAreas/index.tsx, frontend/src/features/Dashboard/components/Pdf/icons/ArrowRight.tsx, frontend/src/features/layersSelector/utils/LayerSelector.style.ts
Cela permet d'éviter un dépassement de l'encadré qui vient mordre sur le commentaire ou des photos
- Resolve #2497
----
=> [Brief] Afficher les liens legicem des zones reg liées à une ZDV en dessous de l'image si plus de deux liens
